/*
 * FuelCell_USART.h
 *
 * Created: 2015-12-05 6:00:22 PM
 *  Author: Reegan
 */ 


#ifndef FUELCELL_USART_H_
#define FUELCELL_USART_H_

void USARTInit(void);


#  define TARGET_PBCCLK_FREQ_HZ 7500000  // PBA clock target frequency, in Hz see init.c

#  define DISPLAY_USART                 (&AVR32_USART3)
#  define DISPLAY_USART_RX_PIN          AVR32_USART3_RXD_2_PIN
#  define DISPLAY_USART_RX_FUNCTION     AVR32_USART3_RXD_2_FUNCTION
#  define DISPLAY_USART_TX_PIN          AVR32_USART3_TXD_2_PIN
#  define DISPLAY_USART_TX_FUNCTION     AVR32_USART3_TXD_2_FUNCTION
#  define DISPLAY_USART_CLOCK_MASK      AVR32_USART3_CLK_PBA

#  define DISPLAY_PDCA_CLOCK_HSB        AVR32_PDCA_CLK_HSB
#  define DISPLAY_PDCA_CLOCK_PB         AVR32_PDCA_CLK_PBC

#define LOG_USART (&AVR32_USART0)
#define LOG_USART_RX_PIN		AVR32_USART0_RXD_1_PIN //pin is gpio pin 73
#define LOG_USART_RX_FUNCTION	AVR32_USART0_RXD_1_FUNCTION
#define LOG_USART_TX_PIN		AVR32_USART0_TXD_1_PIN //pin is gpio pin 72
#define LOG_USART_TX_FUNCTION	AVR32_USART0_TXD_1_FUNCTION
#define LOG_USART_CLOCK_MASK	AVR32_USART0_CLK_PBA

#define LOG_PDCA_CLOCK_HSB		AVR32_PDCA_CLK_HSB
#define LOG_PDCA_CLOCK_PB		AVR32_PDCA_CLK_PBC


#endif /* FUELCELL_USART_H_ */