/*
 * FuelCell_USART.h
 *
 * Created: 2015-12-05 6:00:22 PM
 *  Author: Reegan
 */ 


#ifndef FUELCELL_USART_H_
#define FUELCELL_USART_H_

void USARTInit(void);


#  define TARGET_PBCCLK_FREQ_HZ 7500000  // PBA clock target frequency, in Hz see init.c

#define LOG_USART (&AVR32_USART0)
#define LOG_USART_RX_PIN		AVR32_USART0_RXD_PIN //pin is gpio pin 73
#define LOG_USART_RX_FUNCTION	AVR32_USART0_RXD_FUNCTION
#define LOG_USART_TX_PIN		AVR32_USART0_TXD_PIN //pin is gpio pin 72
#define LOG_USART_TX_FUNCTION	AVR32_USART0_TXD_FUNCTION
#define LOG_USART_CLOCK_MASK	AVR32_USART0_CLK_PBA
#define LOG_PDCA_CLOCK_HSB		AVR32_PDCA_CLK_HSB
#define LOG_PDCA_CLOCK_PB		AVR32_PDCA_CLK_PBC

#define LOG1_USART (&AVR32_USART0)
#define LOG1_USART_RX_PIN		AVR32_USART0_RXD_1_PIN //pin is gpio pin 73
#define LOG1_USART_RX_FUNCTION	AVR32_USART0_RXD_1_FUNCTION
#define LOG1_USART_TX_PIN		AVR32_USART0_TXD_1_PIN //pin is gpio pin 72
#define LOG1_USART_TX_FUNCTION	AVR32_USART0_TXD_1_FUNCTION
#define LOG1_USART_CLOCK_MASK	AVR32_USART0_CLK_PBA
#define LOG1_PDCA_CLOCK_HSB		AVR32_PDCA_CLK_HSB
#define LOG1_PDCA_CLOCK_PB		AVR32_PDCA_CLK_PBC

#define LOG2_USART (&AVR32_USART1)
#define LOG2_USART_RX_PIN		AVR32_USART1_RXD_0_1_PIN //pin is gpio pin 73
#define LOG2_USART_RX_FUNCTION	AVR32_USART1_RXD_0_1_FUNCTION
#define LOG2_USART_TX_PIN		AVR32_USART1_TXD_0_1_PIN //pin is gpio pin 72
#define LOG2_USART_TX_FUNCTION	AVR32_USART1_TXD_0_1_FUNCTION
#define LOG2_USART_CLOCK_MASK	AVR32_USART0_CLK_PBA
#define LOG2_PDCA_CLOCK_HSB		AVR32_PDCA_CLK_HSB
#define LOG2_PDCA_CLOCK_PB		AVR32_PDCA_CLK_PBC

#define LOG3_USART (&AVR32_USART1)
#define LOG3_USART_RX_PIN		AVR32_USART1_RXD_1_PIN //pin is gpio pin 73
#define LOG3_USART_RX_FUNCTION	AVR32_USART1_RXD_1_FUNCTION
#define LOG3_USART_TX_PIN		AVR32_USART1_TXD_1_PIN //pin is gpio pin 72
#define LOG3_USART_TX_FUNCTION	AVR32_USART1_TXD_1_FUNCTION
#define LOG3_USART_CLOCK_MASK	AVR32_USART0_CLK_PBA
#define LOG3_PDCA_CLOCK_HSB		AVR32_PDCA_CLK_HSB
#define LOG3_PDCA_CLOCK_PB		AVR32_PDCA_CLK_PBC

#define LOG4_USART (&AVR32_USART2)
#define LOG4_USART_RX_PIN		AVR32_USART2_RXD_PIN //pin is gpio pin 73
#define LOG4_USART_RX_FUNCTION	AVR32_USART2_RXD_FUNCTION
#define LOG4_USART_TX_PIN		AVR32_USART2_TXD_PIN //pin is gpio pin 72
#define LOG4_USART_TX_FUNCTION	AVR32_USART2_TXD_FUNCTION
#define LOG4_USART_CLOCK_MASK	AVR32_USART2_CLK_PBA
#define LOG2_PDCA_CLOCK_HSB		AVR32_PDCA_CLK_HSB
#define LOG2_PDCA_CLOCK_PB		AVR32_PDCA_CLK_PBC

#define LOG5_USART (&AVR32_USART2)
#define LOG5_USART_RX_PIN		AVR32_USART2_RXD_1_PIN //pin is gpio pin 73
#define LOG5_USART_RX_FUNCTION	AVR32_USART2_RXD_1_FUNCTION
#define LOG5_USART_TX_PIN		AVR32_USART2_TXD_1_PIN //pin is gpio pin 72
#define LOG5_USART_TX_FUNCTION	AVR32_USART2_TXD_1_FUNCTION
#define LOG5_USART_CLOCK_MASK	AVR32_USART2_CLK_PBA
#define LOG5_PDCA_CLOCK_HSB		AVR32_PDCA_CLK_HSB
#define LOG5_PDCA_CLOCK_PB		AVR32_PDCA_CLK_PBC

#define LOG5_USART (&AVR32_USART2)
#define LOG5_USART_RX_PIN		AVR32_USART2_RXD_0_0_PIN //pin is gpio pin 73
#define LOG5_USART_RX_FUNCTION	AVR32_USART2_RXD_0_0_FUNCTION
#define LOG5_USART_TX_PIN		AVR32_USART2_TXD_0_0_PIN //pin is gpio pin 72
#define LOG5_USART_TX_FUNCTION	AVR32_USART2_TXD_0_0_FUNCTION
#define LOG5_USART_CLOCK_MASK	AVR32_USART2_CLK_PBA
#define LOG5_PDCA_CLOCK_HSB		AVR32_PDCA_CLK_HSB
#define LOG5_PDCA_CLOCK_PB		AVR32_PDCA_CLK_PBC

#define LOG6_USART (&AVR32_USART2)
#define LOG6_USART_RX_PIN		AVR32_USART2_RXD_0_1_PIN //pin is gpio pin 73
#define LOG6_USART_RX_FUNCTION	AVR32_USART2_RXD_0_1_FUNCTION
#define LOG6_USART_TX_PIN		AVR32_USART2_TXD_0_1_PIN //pin is gpio pin 72
#define LOG6_USART_TX_FUNCTION	AVR32_USART2_TXD_0_1_FUNCTION
#define LOG6_USART_CLOCK_MASK	AVR32_USART2_CLK_PBA
#define LOG6_PDCA_CLOCK_HSB		AVR32_PDCA_CLK_HSB
#define LOG6_PDCA_CLOCK_PB		AVR32_PDCA_CLK_PBC

#  define DISPLAY_USART                 (&AVR32_USART3)
#  define DISPLAY_USART_RX_PIN          AVR32_USART3_RXD_PIN
#  define DISPLAY_USART_RX_FUNCTION     AVR32_USART3_RXD_FUNCTION
#  define DISPLAY_USART_TX_PIN          AVR32_USART3_TXD_PIN
#  define DISPLAY_USART_TX_FUNCTION     AVR32_USART3_TXD_FUNCTION
#  define DISPLAY_USART_CLOCK_MASK      AVR32_USART3_CLK_PBA
#  define DISPLAY_PDCA_CLOCK_HSB        AVR32_PDCA_CLK_HSB
#  define DISPLAY_PDCA_CLOCK_PB         AVR32_PDCA_CLK_PBC

#  define DISPLAY1_USART                 (&AVR32_USART3)
#  define DISPLAY1_USART_RX_PIN          AVR32_USART3_RXD_2_PIN
#  define DISPLAY1_USART_RX_FUNCTION     AVR32_USART3_RXD_2_FUNCTION
#  define DISPLAY1_USART_TX_PIN          AVR32_USART3_TXD_2_PIN
#  define DISPLAY1_USART_TX_FUNCTION     AVR32_USART3_TXD_2_FUNCTION
#  define DISPLAY1_USART_CLOCK_MASK      AVR32_USART3_CLK_PBA
#  define DISPLAY1_PDCA_CLOCK_HSB        AVR32_PDCA_CLK_HSB
#  define DISPLAY1_PDCA_CLOCK_PB         AVR32_PDCA_CLK_PBC

#endif /* FUELCELL_USART_H_ */