PWM4 Example for uc3c_ek: flashc.h File Reference
flashc.h File Reference
FLASHC driver for AVR32 UC3.
#include <avr32/io.h>
#include <stddef.h>
#include "compiler.h"
Defines
#define AVR32_FLASHC_REGIONS
Number of flash regions defined by the FLASHC.
Functions
FLASHC Protection Mechanisms
void flashc_activate_security_bit (void)
Activates the Security bit.
unsigned int flashc_get_bootloader_protected_size (void)
Gets the bootloader protected size.
Bool flashc_is_external_privileged_fetch_locked (void)
Tells whether external privileged fetch is locked.
Bool flashc_is_page_region_locked (int page_number)
Tells whether the region of a page is locked.
Bool flashc_is_region_locked (unsigned int region)
Tells whether a region is locked.
Bool flashc_is_security_bit_active (void)
Tells whether the Security bit is active.
void flashc_lock_all_regions (Bool lock)
Locks or unlocks all regions.
void flashc_lock_external_privileged_fetch (Bool lock)
Locks or unlocks external privileged fetch.
void flashc_lock_page_region (int page_number, Bool lock)
Locks or unlocks the region of a page.
void flashc_lock_region (unsigned int region, Bool lock)
Locks or unlocks a region.
unsigned int flashc_set_bootloader_protected_size (unsigned int bootprot_size)
Sets the bootloader protected size.
FLASHC Global Commands
void flashc_erase_all (void)
Issues an Erase All command to the FLASHC.
void flashc_no_operation (void)
Issues a No Operation command to the FLASHC.
Access to General-Purpose Fuses
Bool flashc_erase_all_gp_fuses (Bool check)
Erases all general-purpose fuses.
Bool flashc_erase_gp_fuse_bit (unsigned int gp_fuse_bit, Bool check)
Erases a general-purpose fuse bit.
Bool flashc_erase_gp_fuse_bitfield (unsigned int pos, unsigned int width, Bool check)
Erases a general-purpose fuse bit-field.
Bool flashc_erase_gp_fuse_byte (unsigned int gp_fuse_byte, Bool check)
Erases a general-purpose fuse byte.
U64 flashc_read_all_gp_fuses (void)
Reads all general-purpose fuses.
Bool flashc_read_gp_fuse_bit (unsigned int gp_fuse_bit)
Reads a general-purpose fuse bit.
U64 flashc_read_gp_fuse_bitfield (unsigned int pos, unsigned int width)
Reads a general-purpose fuse bit-field.
U8 flashc_read_gp_fuse_byte (unsigned int gp_fuse_byte)
Reads a general-purpose fuse byte.
void flashc_set_all_gp_fuses (U64 value)
Sets all general-purpose fuses with the appropriate erase and write operations.
void flashc_set_gp_fuse_bit (unsigned int gp_fuse_bit, Bool value)
Sets a general-purpose fuse bit with the appropriate erase and write operations.
void flashc_set_gp_fuse_bitfield (unsigned int pos, unsigned int width, U64 value)
Sets a general-purpose fuse bit-field with the appropriate erase and write operations.
void flashc_set_gp_fuse_byte (unsigned int gp_fuse_byte, U8 value)
Sets a general-purpose fuse byte with the appropriate erase and write operations.
void flashc_write_all_gp_fuses (U64 value)
Writes all general-purpose fuses.
void flashc_write_gp_fuse_bit (unsigned int gp_fuse_bit, Bool value)
Writes a general-purpose fuse bit.
void flashc_write_gp_fuse_bitfield (unsigned int pos, unsigned int width, U64 value)
Writes a general-purpose fuse bit-field.
void flashc_write_gp_fuse_byte (unsigned int gp_fuse_byte, U8 value)
Writes a general-purpose fuse byte.
FLASHC Command Control
unsigned int flashc_get_command (void)
Gets the last issued FLASHC command.
unsigned int flashc_get_page_number (void)
Gets the current FLASHC page number.
void flashc_issue_command (unsigned int command, int page_number)
Issues a FLASHC command.
Flash Properties
unsigned int flashc_get_flash_size (void)
Gets the size of the whole flash array.
unsigned int flashc_get_page_count (void)
Gets the total number of pages in the flash array.
unsigned int flashc_get_page_count_per_region (void)
Gets the number of pages in each flash region.
unsigned int flashc_get_page_region (int page_number)
Gets the region number of a page.
unsigned int flashc_get_region_first_page_number (unsigned int region)
Gets the number of the first page of a region.
FLASHC Control
#define flash_set_bus_freq(cpu_f_hz) flashc_set_bus_freq(cpu_f_hz)
Alias on the flashc_set_bus_freq() function.
void flashc_enable_lock_error_int (Bool enable)
Enables or disables the Lock Error interrupt.
void flashc_enable_prog_error_int (Bool enable)
Enables or disables the Programming Error interrupt.
void flashc_enable_ready_int (Bool enable)
Enables or disables the Flash Ready interrupt.
unsigned int flashc_get_wait_state (void)
Gets the number of wait states of flash read accesses.
Bool flashc_is_lock_error_int_enabled (void)
Tells whether the Lock Error interrupt is enabled.
Bool flashc_is_prog_error_int_enabled (void)
Tells whether the Programming Error interrupt is enabled.
Bool flashc_is_ready_int_enabled (void)
Tells whether the Flash Ready interrupt is enabled.
void flashc_set_bus_freq (unsigned int cpu_f_hz)
Depending on the CPU frequency, set the wait states of flash read accesses.
void flashc_set_wait_state (unsigned int wait_state)
Sets the number of wait states of flash read accesses.
Access to Flash Pages
#define flashc_memset(dst, src, src_width, nbytes, erase) TPASTE2(flashc_memset, src_width)((dst), (src), (nbytes), (erase))
Copies nbytes bytes to the flash destination pointed to by dst from the repeated src big-endian source pattern.
void flashc_clear_page_buffer (void)
Clears the page buffer.
Bool flashc_erase_all_pages (Bool check)
Erases all pages within the flash array.
Bool flashc_erase_page (int page_number, Bool check)
Erases a page.
Bool flashc_erase_user_page (Bool check)
Erases the User page.
Bool flashc_is_page_erased (void)
Tells whether the page to which the last Quick Page Read or Quick Page Read User Page command was applied was erased.
volatile void * flashc_memcpy (volatile void *dst, const void *src, size_t nbytes, Bool erase)
Copies nbytes bytes to the flash destination pointed to by dst from the source pointed to by src.
volatile void * flashc_memset16 (volatile void *dst, U16 src, size_t nbytes, Bool erase)
Copies nbytes bytes to the flash destination pointed to by dst from the repeated src big-endian source half-word.
volatile void * flashc_memset32 (volatile void *dst, U32 src, size_t nbytes, Bool erase)
Copies nbytes bytes to the flash destination pointed to by dst from the repeated src big-endian source word.
volatile void * flashc_memset64 (volatile void *dst, U64 src, size_t nbytes, Bool erase)
Copies nbytes bytes to the flash destination pointed to by dst from the repeated src big-endian source double-word.
volatile void * flashc_memset8 (volatile void *dst, U8 src, size_t nbytes, Bool erase)
Copies nbytes bytes to the flash destination pointed to by dst from the repeated src source byte.
Bool flashc_quick_page_read (int page_number)
Applies the Quick Page Read command to a page.
Bool flashc_quick_user_page_read (void)
Issues a Quick Page Read User Page command to the FLASHC.
void flashc_write_page (int page_number)
Writes a page from the page buffer.
void flashc_write_user_page (void)
Writes the User page from the page buffer.
FLASHC Status
void(*volatile flashc_wait_until_ready)(void)
Pointer to the function used by the driver when it needs to wait until the FLASHC is ready to run a new command.
void flashc_default_wait_until_ready (void)
Waits actively until the FLASHC is ready to run a new command.
Bool flashc_is_lock_error (void)
Tells whether a Lock Error has occurred during the last function called that issued one or more FLASHC commands.
Bool flashc_is_programming_error (void)
Tells whether a Programming Error has occurred during the last function called that issued one or more FLASHC commands.
Bool flashc_is_ready (void)
Tells whether the FLASHC is ready to run a new command.
Detailed Description
FLASHC driver for AVR32 UC3.
AVR32 Flash Controller driver module.
Compiler: IAR EWAVR32 and GNU GCC for AVR32
Supported devices: All AVR32 devices with a FLASHC module can be used.
AppNote:
Author:
Atmel Corporation: http://www.atmel.com
Support and FAQ: http://support.atmel.no/
Definition in file flashc.h.
Define Documentation
#define AVR32_FLASHC_REGIONS
Value:
(AVR32_FLASHC_FLASH_SIZE /\
                               (AVR32_FLASHC_PAGES_PR_REGION * AVR32_FLASHC_PAGE_SIZE))
Number of flash regions defined by the FLASHC.
Definition at line 56 of file flashc.h.
Referenced by flashc_get_page_count_per_region(), flashc_is_region_locked(), and flashc_lock_all_regions().
#define flash_set_bus_freq (cpu_f_hz) flashc_set_bus_freq(cpu_f_hz)
Alias on the flashc_set_bus_freq() function.
Parameters:
cpu_f_hz The CPU frequency
Definition at line 131 of file flashc.h.
#define flashc_memset (dst, src, src_width, nbytes, erase) TPASTE2(flashc_memset, src_width)((dst), (src), (nbytes), (erase))
Copies nbytes bytes to the flash destination pointed to by dst from the repeated src big-endian source pattern.
The destination areas that are not within the flash array or the User page are ignored.
All pointer and size alignments are supported.
Parameters:
dst Pointer to flash destination.
src Source double-word.
src_width src width in bits: 8, 16, 32 or 64.
nbytes Number of bytes to set.
erase Whether to erase before writing: TRUE or FALSE.
Returns:
The value of dst.
Warning:
This function may be called with erase set to FALSE only if the destination consists only of erased words, i.e. this function can not be used to write only one bit of a previously written word. E.g., if 0x00000001 then 0xFFFFFFFE are written to a word, the resulting value in flash may be different from 0x00000000.
A Lock Error is issued if the command is applied to pages belonging to a locked region or to the bootloader protected area.
Note:
The FLASHC error status returned by flashc_is_lock_error and flashc_is_programming_error is updated.
Definition at line 964 of file flashc.h.
Function Documentation
void flashc_activate_security_bit (void)
Activates the Security bit.
Note:
The FLASHC error status returned by flashc_is_lock_error and flashc_is_programming_error is updated.
Definition at line 346 of file flashc.c.
References flashc_issue_command().
{
  flashc_issue_command(AVR32_FLASHC_FCMD_CMD_SSB, -1);
}
void flashc_clear_page_buffer (void)
Clears the page buffer.
This command resets all bits in the page buffer to one. Write accesses to the page buffer can only change page buffer bits from one to zero.
Warning:
The page buffer is not automatically reset after a page write.
Note:
The FLASHC error status returned by flashc_is_lock_error and flashc_is_programming_error is updated.
Definition at line 621 of file flashc.c.
References flashc_issue_command().
Referenced by flashc_memcpy(), and flashc_memset64().
{
  flashc_issue_command(AVR32_FLASHC_FCMD_CMD_CPB, -1);
}
void flashc_default_wait_until_ready (void)
Waits actively until the FLASHC is ready to run a new command.
This is the default function assigned to flashc_wait_until_ready.
Definition at line 233 of file flashc.c.
References flashc_is_ready().
{
  while (!flashc_is_ready());
}
void flashc_enable_lock_error_int (Bool enable)
Enables or disables the Lock Error interrupt.
Parameters:
enable Whether to enable the Lock Error interrupt: TRUE or FALSE.
Definition at line 197 of file flashc.c.
References FALSE, u_avr32_flashc_fcr_t::fcr, and u_avr32_flashc_fcr_t::FCR.
{
  u_avr32_flashc_fcr_t u_avr32_flashc_fcr = {AVR32_FLASHC.fcr};
  u_avr32_flashc_fcr.FCR.locke = (enable != FALSE);
  AVR32_FLASHC.fcr = u_avr32_flashc_fcr.fcr;
}
void flashc_enable_prog_error_int (Bool enable)
Enables or disables the Programming Error interrupt.
Parameters:
enable Whether to enable the Programming Error interrupt: TRUE or FALSE.
Definition at line 211 of file flashc.c.
References FALSE, u_avr32_flashc_fcr_t::fcr, and u_avr32_flashc_fcr_t::FCR.
{
  u_avr32_flashc_fcr_t u_avr32_flashc_fcr = {AVR32_FLASHC.fcr};
  u_avr32_flashc_fcr.FCR.proge = (enable != FALSE);
  AVR32_FLASHC.fcr = u_avr32_flashc_fcr.fcr;
}
void flashc_enable_ready_int (Bool enable)
Enables or disables the Flash Ready interrupt.
Parameters:
enable Whether to enable the Flash Ready interrupt: TRUE or FALSE.
Definition at line 183 of file flashc.c.
References FALSE, u_avr32_flashc_fcr_t::fcr, and u_avr32_flashc_fcr_t::FCR.
{
  u_avr32_flashc_fcr_t u_avr32_flashc_fcr = {AVR32_FLASHC.fcr};
  u_avr32_flashc_fcr.FCR.frdy = (enable != FALSE);
  AVR32_FLASHC.fcr = u_avr32_flashc_fcr.fcr;
}
void flashc_erase_all (void)
Issues an Erase All command to the FLASHC.
This command erases all bits in the flash array, the general-purpose fuse bits and the Security bit. The User page is not erased.
This command also ensures that all volatile memories, such as register file and RAMs, are erased before the Security bit is erased, i.e. deactivated.
Warning:
A Lock Error is issued if at least one region is locked or the bootloader protection is active.
Note:
The FLASHC error status returned by flashc_is_lock_error and flashc_is_programming_error is updated.
An erase operation can only set bits.
Definition at line 326 of file flashc.c.
References flashc_issue_command().
{
  flashc_issue_command(AVR32_FLASHC_FCMD_CMD_EA, -1);
}
Bool flashc_erase_all_gp_fuses (Bool check)
Erases all general-purpose fuses.
Parameters:
check Whether to check erase: TRUE or FALSE.
Returns:
Whether the erase succeeded or always TRUE if erase check was not requested.
Warning:
A Lock Error is issued if the Security bit is active.
Note:
The FLASHC error status returned by flashc_is_lock_error and flashc_is_programming_error is updated.
An erase operation can only set bits.
The actual number of general-purpose fuse bits implemented by hardware is given by AVR32_FLASHC_GPF_NUM. The other bits among the 64 are fixed at 1 by hardware.
Definition at line 501 of file flashc.c.
References flashc_issue_command(), flashc_read_all_gp_fuses(), and TRUE.
Referenced by flashc_erase_gp_fuse_byte(), and flashc_set_all_gp_fuses().
{
  flashc_issue_command(AVR32_FLASHC_FCMD_CMD_EAGPF, -1);
  return (check) ? (flashc_read_all_gp_fuses() == 0xFFFFFFFFFFFFFFFFULL) : TRUE;
}
Bool flashc_erase_all_pages (Bool check)
Erases all pages within the flash array.
Parameters:
check Whether to check erase: TRUE or FALSE.
Returns:
Whether the erase succeeded or always TRUE if erase check was not requested.
Warning:
A Lock Error is issued if at least one region is locked or the bootloader protection is active.
Note:
The FLASHC error status returned by flashc_is_lock_error and flashc_is_programming_error is updated.
An erase operation can only set bits.
Definition at line 654 of file flashc.c.
References flashc_erase_page(), flashc_error_status, flashc_get_page_count(), and TRUE.
{
  Bool all_pages_erased = TRUE;
  unsigned int error_status = 0;
  unsigned int page_number = flashc_get_page_count();
  while (page_number)
  {
    all_pages_erased &= flashc_erase_page(--page_number, check);
    error_status |= flashc_error_status;
  }
  flashc_error_status = error_status;
  return all_pages_erased;
}
Bool flashc_erase_gp_fuse_bit (unsigned int gp_fuse_bit, Bool check)
Erases a general-purpose fuse bit.
Parameters:
gp_fuse_bit The general-purpose fuse bit: 0 to 63.
check Whether to check erase: TRUE or FALSE.
Returns:
Whether the erase succeeded or always TRUE if erase check was not requested.
Warning:
A Lock Error is issued if the Security bit is active and the command is applied to BOOTPROT or EPFL fuses.
Note:
The FLASHC error status returned by flashc_is_lock_error and flashc_is_programming_error is updated.
An erase operation can only set bits.
The actual number of general-purpose fuse bits implemented by hardware is given by AVR32_FLASHC_GPF_NUM. The other bits among the 64 are fixed at 1 by hardware.
Definition at line 458 of file flashc.c.
References flashc_issue_command(), flashc_read_gp_fuse_bit(), and TRUE.
Referenced by flashc_erase_gp_fuse_bitfield(), and flashc_set_gp_fuse_bit().
{
  flashc_issue_command(AVR32_FLASHC_FCMD_CMD_EGPB, gp_fuse_bit & 0x3F);
  return (check) ? flashc_read_gp_fuse_bit(gp_fuse_bit) : TRUE;
}
Bool flashc_erase_gp_fuse_bitfield (unsigned int pos, unsigned int width, Bool check)
Erases a general-purpose fuse bit-field.
Parameters:
pos The bit-position of the general-purpose fuse bit-field: 0 to 63.
width The bit-width of the general-purpose fuse bit-field: 0 to 64.
check Whether to check erase: TRUE or FALSE.
Returns:
Whether the erase succeeded or always TRUE if erase check was not requested.
Warning:
A Lock Error is issued if the Security bit is active and the command is applied to BOOTPROT or EPFL fuses.
Note:
The FLASHC error status returned by flashc_is_lock_error and flashc_is_programming_error is updated.
An erase operation can only set bits.
The actual number of general-purpose fuse bits implemented by hardware is given by AVR32_FLASHC_GPF_NUM. The other bits among the 64 are fixed at 1 by hardware.
Definition at line 465 of file flashc.c.
References FALSE, flashc_erase_gp_fuse_bit(), flashc_error_status, flashc_read_gp_fuse_bitfield(), and TRUE.
{
  unsigned int error_status = 0;
  unsigned int gp_fuse_bit;
  pos &= 0x3F;
  width = min(width, 64);
  for (gp_fuse_bit = pos; gp_fuse_bit < pos + width; gp_fuse_bit++)
  {
    flashc_erase_gp_fuse_bit(gp_fuse_bit, FALSE);
    error_status |= flashc_error_status;
  }
  flashc_error_status = error_status;
  return (check) ? (flashc_read_gp_fuse_bitfield(pos, width) == (1ULL << width) - 1) : TRUE;
}
Bool flashc_erase_gp_fuse_byte (unsigned int gp_fuse_byte, Bool check)
Erases a general-purpose fuse byte.
Parameters:
gp_fuse_byte The general-purpose fuse byte: 0 to 7.
check Whether to check erase: TRUE or FALSE.
Returns:
Whether the erase succeeded or always TRUE if erase check was not requested.
Warning:
A Lock Error is issued if the Security bit is active.
Note:
The FLASHC error status returned by flashc_is_lock_error and flashc_is_programming_error is updated.
An erase operation can only set bits.
The actual number of general-purpose fuse bits implemented by hardware is given by AVR32_FLASHC_GPF_NUM. The other bits among the 64 are fixed at 1 by hardware.
Definition at line 481 of file flashc.c.
References FALSE, flashc_erase_all_gp_fuses(), flashc_error_status, flashc_read_all_gp_fuses(), flashc_read_gp_fuse_byte(), flashc_write_gp_fuse_byte(), and TRUE.
Referenced by flashc_set_gp_fuse_byte().
{
  unsigned int error_status;
  unsigned int current_gp_fuse_byte;
  U64 value = flashc_read_all_gp_fuses();
  flashc_erase_all_gp_fuses(FALSE);
  error_status = flashc_error_status;
  for (current_gp_fuse_byte = 0; current_gp_fuse_byte < 8; current_gp_fuse_byte++, value >>= 8)
  {
    if (current_gp_fuse_byte != gp_fuse_byte)
    {
      flashc_write_gp_fuse_byte(current_gp_fuse_byte, value);
      error_status |= flashc_error_status;
    }
  }
  flashc_error_status = error_status;
  return (check) ? (flashc_read_gp_fuse_byte(gp_fuse_byte) == 0xFF) : TRUE;
}
Bool flashc_erase_page (int page_number, Bool check)
Erases a page.
Parameters:
page_number The page number:
0 to (flashc_get_page_count() - 1): a page number within the flash array;
< 0: the current page number.
check Whether to check erase: TRUE or FALSE.
Returns:
Whether the erase succeeded or always TRUE if erase check was not requested.
Warning:
A Lock Error is issued if the command is applied to a page belonging to a locked region or to the bootloader protected area.
Note:
The FLASHC error status returned by flashc_is_lock_error and flashc_is_programming_error is updated.
An erase operation can only set bits.
Definition at line 640 of file flashc.c.
References flashc_error_status, flashc_issue_command(), flashc_quick_page_read(), and TRUE.
Referenced by flashc_erase_all_pages(), flashc_memcpy(), and flashc_memset64().
{
  Bool page_erased = TRUE;
  flashc_issue_command(AVR32_FLASHC_FCMD_CMD_EP, page_number);
  if (check)
  {
    unsigned int error_status = flashc_error_status;
    page_erased = flashc_quick_page_read(-1);
    flashc_error_status |= error_status;
  }
  return page_erased;
}
Bool flashc_erase_user_page (Bool check)
Erases the User page.
Parameters:
check Whether to check erase: TRUE or FALSE.
Returns:
Whether the erase succeeded or always TRUE if erase check was not requested.
Note:
The FLASHC error status returned by flashc_is_lock_error and flashc_is_programming_error is updated.
An erase operation can only set bits.
Definition at line 682 of file flashc.c.
References flashc_issue_command(), flashc_quick_user_page_read(), and TRUE.
Referenced by flashc_memcpy(), and flashc_memset64().
{
  flashc_issue_command(AVR32_FLASHC_FCMD_CMD_EUP, -1);
  return (check) ? flashc_quick_user_page_read() : TRUE;
}
unsigned int flashc_get_bootloader_protected_size (void)
Gets the bootloader protected size.
Returns:
The bootloader protected size in bytes.
Definition at line 352 of file flashc.c.
References flashc_read_gp_fuse_bitfield().
Referenced by flashc_set_bootloader_protected_size().
{
  unsigned int bootprot = (1 << AVR32_FLASHC_FGPFRLO_BOOTPROT_SIZE) - 1 -
                          flashc_read_gp_fuse_bitfield(AVR32_FLASHC_FGPFRLO_BOOTPROT_OFFSET,
                                                       AVR32_FLASHC_FGPFRLO_BOOTPROT_SIZE);
  return (bootprot) ? AVR32_FLASHC_PAGE_SIZE << bootprot : 0;
}
unsigned int flashc_get_command (void)
Gets the last issued FLASHC command.
Returns:
The last issued FLASHC command.
Definition at line 286 of file flashc.c.
{
  return (AVR32_FLASHC.fcmd & AVR32_FLASHC_FCMD_CMD_MASK) >> AVR32_FLASHC_FCMD_CMD_OFFSET;
}
unsigned int flashc_get_flash_size (void)
Gets the size of the whole flash array.
Returns:
The size of the whole flash array in bytes.
Definition at line 78 of file flashc.c.
Referenced by flashc_get_page_count(), flashc_memcpy(), and flashc_memset64().
{
#if (AVR32_FLASHC_H_VERSION >= 300)
  static const unsigned int FLASH_SIZE[1 << AVR32_FLASHC_PR_FSZ_SIZE] =
  {
      4 << 10,
      8 << 10,
      16 << 10,
      32 << 10,
      48 << 10,
      64 << 10,
      96  << 10,
     128 << 10,
     192 << 10,
     256 << 10,
     384 << 10,
     512 << 10,
     768 << 10,
    1024 << 10,
    2048 << 10
  };
  return FLASH_SIZE[(AVR32_FLASHC.pr & AVR32_FLASHC_PR_FSZ_MASK) >> AVR32_FLASHC_PR_FSZ_OFFSET];
#else // in older flashc version, FSZ is located in FSR register
  static const unsigned int FLASH_SIZE[1 << AVR32_FLASHC_FSR_FSZ_SIZE] =
  {
      32 << 10,
      64 << 10,
     128 << 10,
     256 << 10,
     384 << 10,
     512 << 10,
     768 << 10,
    1024 << 10
  };
  return FLASH_SIZE[(AVR32_FLASHC.fsr & AVR32_FLASHC_FSR_FSZ_MASK) >> AVR32_FLASHC_FSR_FSZ_OFFSET];
#endif
}
unsigned int flashc_get_page_count (void)
Gets the total number of pages in the flash array.
Returns:
The total number of pages in the flash array.
Definition at line 117 of file flashc.c.
References flashc_get_flash_size().
Referenced by flashc_erase_all_pages(), and flashc_get_page_count_per_region().
{
  return flashc_get_flash_size() / AVR32_FLASHC_PAGE_SIZE;
}
unsigned int flashc_get_page_count_per_region (void)
Gets the number of pages in each flash region.
Returns:
The number of pages in each flash region.
Definition at line 123 of file flashc.c.
References AVR32_FLASHC_REGIONS, and flashc_get_page_count().
Referenced by flashc_get_page_region(), and flashc_get_region_first_page_number().
{
  return flashc_get_page_count() / AVR32_FLASHC_REGIONS;
}
unsigned int flashc_get_page_number (void)
Gets the current FLASHC page number.
Returns:
The current FLASHC page number.
Definition at line 292 of file flashc.c.
Referenced by flashc_get_page_region().
{
  return (AVR32_FLASHC.fcmd & AVR32_FLASHC_FCMD_PAGEN_MASK) >> AVR32_FLASHC_FCMD_PAGEN_OFFSET;
}
unsigned int flashc_get_page_region (int page_number)
Gets the region number of a page.
Parameters:
page_number The page number:
0 to (flashc_get_page_count() - 1): a page number within the flash array;
< 0: the current page number.
Returns:
The region number of the specified page.
Definition at line 129 of file flashc.c.
References flashc_get_page_count_per_region(), and flashc_get_page_number().
Referenced by flashc_is_page_region_locked().
{
  return ((page_number >= 0) ? page_number : flashc_get_page_number()) / flashc_get_page_count_per_region();
}
unsigned int flashc_get_region_first_page_number (unsigned int region)
Gets the number of the first page of a region.
Parameters:
region The region number: 0 to (AVR32_FLASHC_REGIONS - 1).
Returns:
The number of the first page of the specified region.
Definition at line 135 of file flashc.c.
References flashc_get_page_count_per_region().
Referenced by flashc_lock_region().
{
  return region * flashc_get_page_count_per_region();
}
unsigned int flashc_get_wait_state (void)
Gets the number of wait states of flash read accesses.
Returns:
The number of wait states of flash read accesses.
Definition at line 149 of file flashc.c.
{
  return (AVR32_FLASHC.fcr & AVR32_FLASHC_FCR_FWS_MASK) >> AVR32_FLASHC_FCR_FWS_OFFSET;
}
Bool flashc_is_external_privileged_fetch_locked (void)
Tells whether external privileged fetch is locked.
Returns:
Whether external privileged fetch is locked.
Definition at line 377 of file flashc.c.
References flashc_read_gp_fuse_bit().
{
  return (!flashc_read_gp_fuse_bit(AVR32_FLASHC_FGPFRLO_EPFL_OFFSET));
}
Bool flashc_is_lock_error (void)
Tells whether a Lock Error has occurred during the last function called that issued one or more FLASHC commands.
Returns:
Whether a Lock Error has occurred during the last function called that issued one or more FLASHC commands.
Definition at line 266 of file flashc.c.
References flashc_error_status.
{
  return ((flashc_error_status & AVR32_FLASHC_FSR_LOCKE_MASK) != 0);
}
Bool flashc_is_lock_error_int_enabled (void)
Tells whether the Lock Error interrupt is enabled.
Returns:
Whether the Lock Error interrupt is enabled.
Definition at line 191 of file flashc.c.
{
  return ((AVR32_FLASHC.fcr & AVR32_FLASHC_FCR_LOCKE_MASK) != 0);
}
Bool flashc_is_page_erased (void)
Tells whether the page to which the last Quick Page Read or Quick Page Read User Page command was applied was erased.
Returns:
Whether the page to which the last Quick Page Read or Quick Page Read User Page command was applied was erased.
Definition at line 627 of file flashc.c.
Referenced by flashc_quick_page_read(), and flashc_quick_user_page_read().
{
  return ((AVR32_FLASHC.fsr & AVR32_FLASHC_FSR_QPRR_MASK) != 0);
}
Bool flashc_is_page_region_locked (int page_number)
Tells whether the region of a page is locked.
Parameters:
page_number The page number:
0 to (flashc_get_page_count() - 1): a page number within the flash array;
< 0: the current page number.
Returns:
Whether the region of the specified page is locked.
Definition at line 389 of file flashc.c.
References flashc_get_page_region(), and flashc_is_region_locked().
{
  return flashc_is_region_locked(flashc_get_page_region(page_number));
}
Bool flashc_is_prog_error_int_enabled (void)
Tells whether the Programming Error interrupt is enabled.
Returns:
Whether the Programming Error interrupt is enabled.
Definition at line 205 of file flashc.c.
{
  return ((AVR32_FLASHC.fcr & AVR32_FLASHC_FCR_PROGE_MASK) != 0);
}
Bool flashc_is_programming_error (void)
Tells whether a Programming Error has occurred during the last function called that issued one or more FLASHC commands.
Returns:
Whether a Programming Error has occurred during the last function called that issued one or more FLASHC commands.
Definition at line 272 of file flashc.c.
References flashc_error_status.
{
  return ((flashc_error_status & AVR32_FLASHC_FSR_PROGE_MASK) != 0);
}
Bool flashc_is_ready (void)
Tells whether the FLASHC is ready to run a new command.
Returns:
Whether the FLASHC is ready to run a new command.
Definition at line 227 of file flashc.c.
Referenced by flashc_default_wait_until_ready().
{
  return ((AVR32_FLASHC.fsr & AVR32_FLASHC_FSR_FRDY_MASK) != 0);
}
Bool flashc_is_ready_int_enabled (void)
Tells whether the Flash Ready interrupt is enabled.
Returns:
Whether the Flash Ready interrupt is enabled.
Definition at line 177 of file flashc.c.
{
  return ((AVR32_FLASHC.fcr & AVR32_FLASHC_FCR_FRDY_MASK) != 0);
}
Bool flashc_is_region_locked (unsigned int region)
Tells whether a region is locked.
Parameters:
region The region number: 0 to (AVR32_FLASHC_REGIONS - 1).
Returns:
Whether the specified region is locked.
Definition at line 395 of file flashc.c.
References AVR32_FLASHC_REGIONS.
Referenced by flashc_is_page_region_locked().
{
  return ((AVR32_FLASHC.fsr & AVR32_FLASHC_FSR_LOCK0_MASK << (region & (AVR32_FLASHC_REGIONS - 1))) != 0);
}
Bool flashc_is_security_bit_active (void)
Tells whether the Security bit is active.
Returns:
Whether the Security bit is active.
Definition at line 340 of file flashc.c.
{
  return ((AVR32_FLASHC.fsr & AVR32_FLASHC_FSR_SECURITY_MASK) != 0);
}
void flashc_issue_command (unsigned int command, int page_number)
Issues a FLASHC command.
Parameters:
command The command: AVR32_FLASHC_FCMD_CMD_x.
page_number The page number to apply the command to:
0 to (flashc_get_page_count() - 1): a page number within the flash array;
< 0: use this to apply the command to the current page number or if the command does not apply to any page number;
this argument may have other meanings according to the command. See the FLASHC chapter of the MCU datasheet.
Warning:
A Lock Error is issued if the command violates the protection mechanism.
A Programming Error is issued if the command is invalid.
Note:
The FLASHC error status returned by flashc_is_lock_error and flashc_is_programming_error is updated.
Definition at line 298 of file flashc.c.
References u_avr32_flashc_fcmd_t::FCMD, u_avr32_flashc_fcmd_t::fcmd, flashc_error_status, flashc_get_error_status(), and flashc_wait_until_ready.
Referenced by flashc_activate_security_bit(), flashc_clear_page_buffer(), flashc_erase_all(), flashc_erase_all_gp_fuses(), flashc_erase_gp_fuse_bit(), flashc_erase_page(), flashc_erase_user_page(), flashc_lock_page_region(), flashc_no_operation(), flashc_quick_page_read(), flashc_quick_user_page_read(), flashc_write_gp_fuse_bit(), flashc_write_gp_fuse_byte(), flashc_write_page(), and flashc_write_user_page().
{
  u_avr32_flashc_fcmd_t u_avr32_flashc_fcmd;
  flashc_wait_until_ready();
  u_avr32_flashc_fcmd.fcmd = AVR32_FLASHC.fcmd;
  u_avr32_flashc_fcmd.FCMD.cmd = command;
  if (page_number >= 0) u_avr32_flashc_fcmd.FCMD.pagen = page_number;
  u_avr32_flashc_fcmd.FCMD.key = AVR32_FLASHC_FCMD_KEY_KEY;
  AVR32_FLASHC.fcmd = u_avr32_flashc_fcmd.fcmd;
  flashc_error_status = flashc_get_error_status();
  flashc_wait_until_ready();
}
void flashc_lock_all_regions (Bool lock)
Locks or unlocks all regions.
Parameters:
lock Whether to lock the regions: TRUE or FALSE.
Note:
The FLASHC error status returned by flashc_is_lock_error and flashc_is_programming_error is updated.
Definition at line 413 of file flashc.c.
References AVR32_FLASHC_REGIONS, flashc_error_status, and flashc_lock_region().
{
  unsigned int error_status = 0;
  unsigned int region = AVR32_FLASHC_REGIONS;
  while (region)
  {
    flashc_lock_region(--region, lock);
    error_status |= flashc_error_status;
  }
  flashc_error_status = error_status;
}
void flashc_lock_external_privileged_fetch (Bool lock)
Locks or unlocks external privileged fetch.
Parameters:
lock Whether to lock external privileged fetch: TRUE or FALSE.
Warning:
A Lock Error is issued if the Security bit is active.
Note:
The FLASHC error status returned by flashc_is_lock_error and flashc_is_programming_error is updated.
Definition at line 383 of file flashc.c.
References flashc_set_gp_fuse_bit().
{
  flashc_set_gp_fuse_bit(AVR32_FLASHC_FGPFRLO_EPFL_OFFSET, !lock);
}
void flashc_lock_page_region (int page_number, Bool lock)
Locks or unlocks the region of a page.
Parameters:
page_number The page number:
0 to (flashc_get_page_count() - 1): a page number within the flash array;
< 0: the current page number.
lock Whether to lock the region of the specified page: TRUE or FALSE.
Note:
The FLASHC error status returned by flashc_is_lock_error and flashc_is_programming_error is updated.
Definition at line 401 of file flashc.c.
References flashc_issue_command().
Referenced by flashc_lock_region().
{
  flashc_issue_command((lock) ? AVR32_FLASHC_FCMD_CMD_LP : AVR32_FLASHC_FCMD_CMD_UP, page_number);
}
void flashc_lock_region (unsigned int region, Bool lock)
Locks or unlocks a region.
Parameters:
region The region number: 0 to (AVR32_FLASHC_REGIONS - 1).
lock Whether to lock the specified region: TRUE or FALSE.
Note:
The FLASHC error status returned by flashc_is_lock_error and flashc_is_programming_error is updated.
Definition at line 407 of file flashc.c.
References flashc_get_region_first_page_number(), and flashc_lock_page_region().
Referenced by flashc_lock_all_regions().
{
  flashc_lock_page_region(flashc_get_region_first_page_number(region), lock);
}
volatile void* flashc_memcpy (volatile void * dst, const void * src, size_t nbytes, Bool erase)
Copies nbytes bytes to the flash destination pointed to by dst from the source pointed to by src.
The destination areas that are not within the flash array or the User page are ignored.
All pointer and size alignments are supported.
Parameters:
dst Pointer to flash destination.
src Pointer to source data.
nbytes Number of bytes to copy.
erase Whether to erase before writing: TRUE or FALSE.
Returns:
The value of dst.
Warning:
If copying takes place between areas that overlap, the behavior is undefined.
This function may be called with erase set to FALSE only if the destination consists only of erased words, i.e. this function can not be used to write only one bit of a previously written word. E.g., if 0x00000001 then 0xFFFFFFFE are written to a word, the resulting value in flash may be different from 0x00000000.
A Lock Error is issued if the command is applied to pages belonging to a locked region or to the bootloader protected area.
Note:
The FLASHC error status returned by flashc_is_lock_error and flashc_is_programming_error is updated.
Definition at line 886 of file flashc.c.
References FALSE, flashc_clear_page_buffer(), flashc_erase_page(), flashc_erase_user_page(), flashc_error_status, flashc_get_flash_size(), flashc_write_page(), flashc_write_user_page(), and TRUE.
{
  // Use aggregated pointers to have several alignments available for a same address.
  UnionCVPtr flash_array_end;
  UnionVPtr dest;
  UnionCPtr source;
  StructCVPtr dest_end;
  UnionCVPtr flash_page_source_end;
  Bool incomplete_flash_page_end;
  Union64 flash_dword;
  Bool flash_dword_pending = FALSE;
  UnionVPtr tmp;
  unsigned int error_status = 0;
  unsigned int i, j;
  // Reformat arguments.
  flash_array_end.u8ptr = AVR32_FLASH + flashc_get_flash_size();
  dest.u8ptr = dst;
  source.u8ptr = src;
  dest_end.u8ptr = dest.u8ptr + nbytes;
  // If destination is outside flash, go to next flash page if any.
  if (dest.u8ptr < AVR32_FLASH)
  {
    source.u8ptr += AVR32_FLASH - dest.u8ptr;
    dest.u8ptr = AVR32_FLASH;
  }
  else if (flash_array_end.u8ptr <= dest.u8ptr && dest.u8ptr < AVR32_FLASHC_USER_PAGE)
  {
    source.u8ptr += AVR32_FLASHC_USER_PAGE - dest.u8ptr;
    dest.u8ptr = AVR32_FLASHC_USER_PAGE;
  }
  // If end of destination is outside flash, move it to the end of the previous flash page if any.
  if (dest_end.u8ptr > AVR32_FLASHC_USER_PAGE + AVR32_FLASHC_USER_PAGE_SIZE)
  {
    dest_end.u8ptr = AVR32_FLASHC_USER_PAGE + AVR32_FLASHC_USER_PAGE_SIZE;
  }
  else if (AVR32_FLASHC_USER_PAGE >= dest_end.u8ptr && dest_end.u8ptr > flash_array_end.u8ptr)
  {
    dest_end.u8ptr = flash_array_end.u8ptr;
  }
  // Align each end of destination pointer with its natural boundary.
  dest_end.u16ptr = (U16 *)Align_down((U32)dest_end.u8ptr, sizeof(U16));
  dest_end.u32ptr = (U32 *)Align_down((U32)dest_end.u16ptr, sizeof(U32));
  dest_end.u64ptr = (U64 *)Align_down((U32)dest_end.u32ptr, sizeof(U64));
  // While end of destination is not reached...
  while (dest.u8ptr < dest_end.u8ptr)
  {
    // Clear the page buffer in order to prepare data for a flash page write.
    flashc_clear_page_buffer();
    error_status |= flashc_error_status;
    // Determine where the source data will end in the current flash page.
    flash_page_source_end.u64ptr =
      (U64 *)min((U32)dest_end.u64ptr,
                 Align_down((U32)dest.u8ptr, AVR32_FLASHC_PAGE_SIZE) + AVR32_FLASHC_PAGE_SIZE);
    // Determine if the current destination page has an incomplete end.
    incomplete_flash_page_end = (Align_down((U32)dest.u8ptr, AVR32_FLASHC_PAGE_SIZE) >=
                                 Align_down((U32)dest_end.u8ptr, AVR32_FLASHC_PAGE_SIZE));
    // If destination does not point to the beginning of the current flash page...
    if (!Test_align((U32)dest.u8ptr, AVR32_FLASHC_PAGE_SIZE))
    {
      // Fill the beginning of the page buffer with the current flash page data.
      // This is required by the hardware, even if page erase is not requested,
      // in order to be able to write successfully to erased parts of flash
      // pages that have already been written to.
      for (tmp.u8ptr = (U8 *)Align_down((U32)dest.u8ptr, AVR32_FLASHC_PAGE_SIZE);
           tmp.u64ptr < (U64 *)Align_down((U32)dest.u8ptr, sizeof(U64));
           tmp.u64ptr++)
        *tmp.u64ptr = *tmp.u64ptr;
      // If destination is not 64-bit aligned...
      if (!Test_align((U32)dest.u8ptr, sizeof(U64)))
      {
        // Fill the beginning of the flash double-word buffer with the current
        // flash page data.
        // This is required by the hardware, even if page erase is not
        // requested, in order to be able to write successfully to erased parts
        // of flash pages that have already been written to.
        for (i = 0; i < Get_align((U32)dest.u8ptr, sizeof(U64)); i++)
          flash_dword.u8[i] = *tmp.u8ptr++;
        // Fill the end of the flash double-word buffer with the source data.
        for (; i < sizeof(U64); i++)
          flash_dword.u8[i] = *source.u8ptr++;
        // Align the destination pointer with its 64-bit boundary.
        dest.u64ptr = (U64 *)Align_down((U32)dest.u8ptr, sizeof(U64));
        // If the current destination double-word is not the last one...
        if (dest.u64ptr < dest_end.u64ptr)
        {
          // Write the flash double-word buffer to the page buffer.
          *dest.u64ptr++ = flash_dword.u64;
        }
        // If the current destination double-word is the last one, the flash
        // double-word buffer must be kept for later.
        else flash_dword_pending = TRUE;
      }
    }
    // Read the source data with the maximal possible alignment and write it to
    // the page buffer with 64-bit alignment.
    switch (Get_align((U32)source.u8ptr, sizeof(U32)))
    {
    case 0:
      for (i = flash_page_source_end.u64ptr - dest.u64ptr; i; i--)
        *dest.u64ptr++ = *source.u64ptr++;
      break;
    case sizeof(U16):
      for (i = flash_page_source_end.u64ptr - dest.u64ptr; i; i--)
      {
        for (j = 0; j < sizeof(U64) / sizeof(U16); j++) flash_dword.u16[j] = *source.u16ptr++;
        *dest.u64ptr++ = flash_dword.u64;
      }
      break;
    default:
      for (i = flash_page_source_end.u64ptr - dest.u64ptr; i; i--)
      {
        for (j = 0; j < sizeof(U64); j++) flash_dword.u8[j] = *source.u8ptr++;
        *dest.u64ptr++ = flash_dword.u64;
      }
    }
    // If the current destination page has an incomplete end...
    if (incomplete_flash_page_end)
    {
      // If the flash double-word buffer is in use, do not initialize it.
      if (flash_dword_pending) i = Get_align((U32)dest_end.u8ptr, sizeof(U64));
      // If the flash double-word buffer is free...
      else
      {
        // Fill the beginning of the flash double-word buffer with the source data.
        for (i = 0; i < Get_align((U32)dest_end.u8ptr, sizeof(U64)); i++)
          flash_dword.u8[i] = *source.u8ptr++;
      }
      // This is required by the hardware, even if page erase is not requested,
      // in order to be able to write successfully to erased parts of flash
      // pages that have already been written to.
      {
        tmp.u8ptr = (volatile U8 *)dest_end.u8ptr;
        // If end of destination is not 64-bit aligned...
        if (!Test_align((U32)dest_end.u8ptr, sizeof(U64)))
        {
          // Fill the end of the flash double-word buffer with the current flash page data.
          for (; i < sizeof(U64); i++)
            flash_dword.u8[i] = *tmp.u8ptr++;
          // Write the flash double-word buffer to the page buffer.
          *dest.u64ptr++ = flash_dword.u64;
        }
        // Fill the end of the page buffer with the current flash page data.
        for (; !Test_align((U32)tmp.u64ptr, AVR32_FLASHC_PAGE_SIZE); tmp.u64ptr++)
          *tmp.u64ptr = *tmp.u64ptr;
      }
    }
    // If the current flash page is in the flash array...
    if (dest.u8ptr <= AVR32_FLASHC_USER_PAGE)
    {
      // Erase the current page if requested and write it from the page buffer.
      if (erase)
      {
        flashc_erase_page(-1, FALSE);
        error_status |= flashc_error_status;
      }
      flashc_write_page(-1);
      error_status |= flashc_error_status;
      // If the end of the flash array is reached, go to the User page.
      if (dest.u8ptr >= flash_array_end.u8ptr)
      {
        source.u8ptr += AVR32_FLASHC_USER_PAGE - dest.u8ptr;
        dest.u8ptr = AVR32_FLASHC_USER_PAGE;
      }
    }
    // If the current flash page is the User page...
    else
    {
      // Erase the User page if requested and write it from the page buffer.
      if (erase)
      {
        flashc_erase_user_page(FALSE);
        error_status |= flashc_error_status;
      }
      flashc_write_user_page();
      error_status |= flashc_error_status;
    }
  }
  // Update the FLASHC error status.
  flashc_error_status = error_status;
  // Return the initial destination pointer as the standard memcpy function does.
  return dst;
}
volatile void* flashc_memset16 (volatile void * dst, U16 src, size_t nbytes, Bool erase)
Copies nbytes bytes to the flash destination pointed to by dst from the repeated src big-endian source half-word.
The destination areas that are not within the flash array or the User page are ignored.
All pointer and size alignments are supported.
Parameters:
dst Pointer to flash destination.
src Source half-word.
nbytes Number of bytes to set.
erase Whether to erase before writing: TRUE or FALSE.
Returns:
The value of dst.
Warning:
This function may be called with erase set to FALSE only if the destination consists only of erased words, i.e. this function can not be used to write only one bit of a previously written word. E.g., if 0x00000001 then 0xFFFFFFFE are written to a word, the resulting value in flash may be different from 0x00000000.
A Lock Error is issued if the command is applied to pages belonging to a locked region or to the bootloader protected area.
Note:
The FLASHC error status returned by flashc_is_lock_error and flashc_is_programming_error is updated.
Definition at line 701 of file flashc.c.
References flashc_memset32().
Referenced by flashc_memset8().
{
  return flashc_memset32(dst, src | (U32)src << 16, nbytes, erase);
}
volatile void* flashc_memset32 (volatile void * dst, U32 src, size_t nbytes, Bool erase)
Copies nbytes bytes to the flash destination pointed to by dst from the repeated src big-endian source word.
The destination areas that are not within the flash array or the User page are ignored.
All pointer and size alignments are supported.
Parameters:
dst Pointer to flash destination.
src Source word.
nbytes Number of bytes to set.
erase Whether to erase before writing: TRUE or FALSE.
Returns:
The value of dst.
Warning:
This function may be called with erase set to FALSE only if the destination consists only of erased words, i.e. this function can not be used to write only one bit of a previously written word. E.g., if 0x00000001 then 0xFFFFFFFE are written to a word, the resulting value in flash may be different from 0x00000000.
A Lock Error is issued if the command is applied to pages belonging to a locked region or to the bootloader protected area.
Note:
The FLASHC error status returned by flashc_is_lock_error and flashc_is_programming_error is updated.
Definition at line 707 of file flashc.c.
References flashc_memset64().
Referenced by flashc_memset16().
{
  return flashc_memset64(dst, src | (U64)src << 32, nbytes, erase);
}
volatile void* flashc_memset64 (volatile void * dst, U64 src, size_t nbytes, Bool erase)
Copies nbytes bytes to the flash destination pointed to by dst from the repeated src big-endian source double-word.
The destination areas that are not within the flash array or the User page are ignored.
All pointer and size alignments are supported.
Parameters:
dst Pointer to flash destination.
src Source double-word.
nbytes Number of bytes to set.
erase Whether to erase before writing: TRUE or FALSE.
Returns:
The value of dst.
Warning:
This function may be called with erase set to FALSE only if the destination consists only of erased words, i.e. this function can not be used to write only one bit of a previously written word. E.g., if 0x00000001 then 0xFFFFFFFE are written to a word, the resulting value in flash may be different from 0x00000000.
A Lock Error is issued if the command is applied to pages belonging to a locked region or to the bootloader protected area.
Note:
The FLASHC error status returned by flashc_is_lock_error and flashc_is_programming_error is updated.
Definition at line 713 of file flashc.c.
References FALSE, flashc_clear_page_buffer(), flashc_erase_page(), flashc_erase_user_page(), flashc_error_status, flashc_get_flash_size(), flashc_write_page(), and flashc_write_user_page().
Referenced by flashc_memset32().
{
  // Use aggregated pointers to have several alignments available for a same address.
  UnionCVPtr flash_array_end;
  UnionVPtr dest;
  Union64 source = {0};
  StructCVPtr dest_end;
  UnionCVPtr flash_page_source_end;
  Bool incomplete_flash_page_end;
  Union64 flash_dword;
  UnionVPtr tmp;
  unsigned int error_status = 0;
  unsigned int i;
  // Reformat arguments.
  flash_array_end.u8ptr = AVR32_FLASH + flashc_get_flash_size();
  dest.u8ptr = dst;
  for (i = (Get_align((U32)dest.u8ptr, sizeof(U64)) - 1) & (sizeof(U64) - 1);
       src; i = (i - 1) & (sizeof(U64) - 1))
  {
    source.u8[i] = src;
    src >>= 8;
  }
  dest_end.u8ptr = dest.u8ptr + nbytes;
  // If destination is outside flash, go to next flash page if any.
  if (dest.u8ptr < AVR32_FLASH)
  {
    dest.u8ptr = AVR32_FLASH;
  }
  else if (flash_array_end.u8ptr <= dest.u8ptr && dest.u8ptr < AVR32_FLASHC_USER_PAGE)
  {
    dest.u8ptr = AVR32_FLASHC_USER_PAGE;
  }
  // If end of destination is outside flash, move it to the end of the previous flash page if any.
  if (dest_end.u8ptr > AVR32_FLASHC_USER_PAGE + AVR32_FLASHC_USER_PAGE_SIZE)
  {
    dest_end.u8ptr = AVR32_FLASHC_USER_PAGE + AVR32_FLASHC_USER_PAGE_SIZE;
  }
  else if (AVR32_FLASHC_USER_PAGE >= dest_end.u8ptr && dest_end.u8ptr > flash_array_end.u8ptr)
  {
    dest_end.u8ptr = flash_array_end.u8ptr;
  }
  // Align each end of destination pointer with its natural boundary.
  dest_end.u16ptr = (U16 *)Align_down((U32)dest_end.u8ptr, sizeof(U16));
  dest_end.u32ptr = (U32 *)Align_down((U32)dest_end.u16ptr, sizeof(U32));
  dest_end.u64ptr = (U64 *)Align_down((U32)dest_end.u32ptr, sizeof(U64));
  // While end of destination is not reached...
  while (dest.u8ptr < dest_end.u8ptr)
  {
    // Clear the page buffer in order to prepare data for a flash page write.
    flashc_clear_page_buffer();
    error_status |= flashc_error_status;
    // Determine where the source data will end in the current flash page.
    flash_page_source_end.u64ptr =
      (U64 *)min((U32)dest_end.u64ptr,
                 Align_down((U32)dest.u8ptr, AVR32_FLASHC_PAGE_SIZE) + AVR32_FLASHC_PAGE_SIZE);
    // Determine if the current destination page has an incomplete end.
    incomplete_flash_page_end = (Align_down((U32)dest.u8ptr, AVR32_FLASHC_PAGE_SIZE) >=
                                 Align_down((U32)dest_end.u8ptr, AVR32_FLASHC_PAGE_SIZE));
    // Use a flash double-word buffer to manage unaligned accesses.
    flash_dword.u64 = source.u64;
    // If destination does not point to the beginning of the current flash page...
    if (!Test_align((U32)dest.u8ptr, AVR32_FLASHC_PAGE_SIZE))
    {
      // Fill the beginning of the page buffer with the current flash page data.
      // This is required by the hardware, even if page erase is not requested,
      // in order to be able to write successfully to erased parts of flash
      // pages that have already been written to.
      for (tmp.u8ptr = (U8 *)Align_down((U32)dest.u8ptr, AVR32_FLASHC_PAGE_SIZE);
           tmp.u64ptr < (U64 *)Align_down((U32)dest.u8ptr, sizeof(U64));
           tmp.u64ptr++)
        *tmp.u64ptr = *tmp.u64ptr;
      // If destination is not 64-bit aligned...
      if (!Test_align((U32)dest.u8ptr, sizeof(U64)))
      {
        // Fill the beginning of the flash double-word buffer with the current
        // flash page data.
        // This is required by the hardware, even if page erase is not
        // requested, in order to be able to write successfully to erased parts
        // of flash pages that have already been written to.
        for (i = 0; i < Get_align((U32)dest.u8ptr, sizeof(U64)); i++)
          flash_dword.u8[i] = *tmp.u8ptr++;
        // Align the destination pointer with its 64-bit boundary.
        dest.u64ptr = (U64 *)Align_down((U32)dest.u8ptr, sizeof(U64));
        // If the current destination double-word is not the last one...
        if (dest.u64ptr < dest_end.u64ptr)
        {
          // Write the flash double-word buffer to the page buffer and reinitialize it.
          *dest.u64ptr++ = flash_dword.u64;
          flash_dword.u64 = source.u64;
        }
      }
    }
    // Write the source data to the page buffer with 64-bit alignment.
    for (i = flash_page_source_end.u64ptr - dest.u64ptr; i; i--)
      *dest.u64ptr++ = source.u64;
    // If the current destination page has an incomplete end...
    if (incomplete_flash_page_end)
    {
      // This is required by the hardware, even if page erase is not requested,
      // in order to be able to write successfully to erased parts of flash
      // pages that have already been written to.
      {
        tmp.u8ptr = (volatile U8 *)dest_end.u8ptr;
        // If end of destination is not 64-bit aligned...
        if (!Test_align((U32)dest_end.u8ptr, sizeof(U64)))
        {
          // Fill the end of the flash double-word buffer with the current flash page data.
          for (i = Get_align((U32)dest_end.u8ptr, sizeof(U64)); i < sizeof(U64); i++)
            flash_dword.u8[i] = *tmp.u8ptr++;
          // Write the flash double-word buffer to the page buffer.
          *dest.u64ptr++ = flash_dword.u64;
        }
        // Fill the end of the page buffer with the current flash page data.
        for (; !Test_align((U32)tmp.u64ptr, AVR32_FLASHC_PAGE_SIZE); tmp.u64ptr++)
          *tmp.u64ptr = *tmp.u64ptr;
      }
    }
    // If the current flash page is in the flash array...
    if (dest.u8ptr <= AVR32_FLASHC_USER_PAGE)
    {
      // Erase the current page if requested and write it from the page buffer.
      if (erase)
      {
        flashc_erase_page(-1, FALSE);
        error_status |= flashc_error_status;
      }
      flashc_write_page(-1);
      error_status |= flashc_error_status;
      // If the end of the flash array is reached, go to the User page.
      if (dest.u8ptr >= flash_array_end.u8ptr)
        dest.u8ptr = AVR32_FLASHC_USER_PAGE;
    }
    // If the current flash page is the User page...
    else
    {
      // Erase the User page if requested and write it from the page buffer.
      if (erase)
      {
        flashc_erase_user_page(FALSE);
        error_status |= flashc_error_status;
      }
      flashc_write_user_page();
      error_status |= flashc_error_status;
    }
  }
  // Update the FLASHC error status.
  flashc_error_status = error_status;
  // Return the initial destination pointer as the standard memset function does.
  return dst;
}
volatile void* flashc_memset8 (volatile void * dst, U8 src, size_t nbytes, Bool erase)
Copies nbytes bytes to the flash destination pointed to by dst from the repeated src source byte.
The destination areas that are not within the flash array or the User page are ignored.
All pointer and size alignments are supported.
Parameters:
dst Pointer to flash destination.
src Source byte.
nbytes Number of bytes to set.
erase Whether to erase before writing: TRUE or FALSE.
Returns:
The value of dst.
Warning:
This function may be called with erase set to FALSE only if the destination consists only of erased words, i.e. this function can not be used to write only one bit of a previously written word. E.g., if 0x00000001 then 0xFFFFFFFE are written to a word, the resulting value in flash may be different from 0x00000000.
A Lock Error is issued if the command is applied to pages belonging to a locked region or to the bootloader protected area.
Note:
The FLASHC error status returned by flashc_is_lock_error and flashc_is_programming_error is updated.
Definition at line 695 of file flashc.c.
References flashc_memset16().
{
  return flashc_memset16(dst, src | (U16)src << 8, nbytes, erase);
}
void flashc_no_operation (void)
Issues a No Operation command to the FLASHC.
Note:
The FLASHC error status returned by flashc_is_lock_error and flashc_is_programming_error is updated.
Definition at line 320 of file flashc.c.
References flashc_issue_command().
{
  flashc_issue_command(AVR32_FLASHC_FCMD_CMD_NOP, -1);
}
Bool flashc_quick_page_read (int page_number)
Applies the Quick Page Read command to a page.
Parameters:
page_number The page number:
0 to (flashc_get_page_count() - 1): a page number within the flash array;
< 0: the current page number.
Returns:
Whether the specified page is erased.
Note:
The FLASHC error status returned by flashc_is_lock_error and flashc_is_programming_error is updated.
Definition at line 633 of file flashc.c.
References flashc_is_page_erased(), and flashc_issue_command().
Referenced by flashc_erase_page().
{
  flashc_issue_command(AVR32_FLASHC_FCMD_CMD_QPR, page_number);
  return flashc_is_page_erased();
}
Bool flashc_quick_user_page_read (void)
Issues a Quick Page Read User Page command to the FLASHC.
Returns:
Whether the User page is erased.
Note:
The FLASHC error status returned by flashc_is_lock_error and flashc_is_programming_error is updated.
Definition at line 675 of file flashc.c.
References flashc_is_page_erased(), and flashc_issue_command().
Referenced by flashc_erase_user_page().
{
  flashc_issue_command(AVR32_FLASHC_FCMD_CMD_QPRUP, -1);
  return flashc_is_page_erased();
}
U64 flashc_read_all_gp_fuses (void)
Reads all general-purpose fuses.
Returns:
The value of all general-purpose fuses as a word.
Note:
The actual number of general-purpose fuse bits implemented by hardware is given by AVR32_FLASHC_GPF_NUM. The other bits among the 64 are fixed at 1 by hardware.
Definition at line 452 of file flashc.c.
Referenced by flashc_erase_all_gp_fuses(), flashc_erase_gp_fuse_byte(), flashc_read_gp_fuse_bit(), flashc_read_gp_fuse_bitfield(), and flashc_read_gp_fuse_byte().
{
  return AVR32_FLASHC.fgpfrlo | (U64)AVR32_FLASHC.fgpfrhi << 32;
}
Bool flashc_read_gp_fuse_bit (unsigned int gp_fuse_bit)
Reads a general-purpose fuse bit.
Parameters:
gp_fuse_bit The general-purpose fuse bit: 0 to 63.
Returns:
The value of the specified general-purpose fuse bit.
Note:
The actual number of general-purpose fuse bits implemented by hardware is given by AVR32_FLASHC_GPF_NUM. The other bits among the 64 are fixed at 1 by hardware.
Definition at line 434 of file flashc.c.
References flashc_read_all_gp_fuses().
Referenced by flashc_erase_gp_fuse_bit(), and flashc_is_external_privileged_fetch_locked().
{
  return ((flashc_read_all_gp_fuses() & 1ULL << (gp_fuse_bit & 0x3F)) != 0);
}
U64 flashc_read_gp_fuse_bitfield (unsigned int pos, unsigned int width)
Reads a general-purpose fuse bit-field.
Parameters:
pos The bit-position of the general-purpose fuse bit-field: 0 to 63.
width The bit-width of the general-purpose fuse bit-field: 0 to 64.
Returns:
The value of the specified general-purpose fuse bit-field.
Note:
The actual number of general-purpose fuse bits implemented by hardware is given by AVR32_FLASHC_GPF_NUM. The other bits among the 64 are fixed at 1 by hardware.
Definition at line 440 of file flashc.c.
References flashc_read_all_gp_fuses().
Referenced by flashc_erase_gp_fuse_bitfield(), and flashc_get_bootloader_protected_size().
{
  return flashc_read_all_gp_fuses() >> (pos & 0x3F) & ((1ULL << min(width, 64)) - 1);
}
U8 flashc_read_gp_fuse_byte (unsigned int gp_fuse_byte)
Reads a general-purpose fuse byte.
Parameters:
gp_fuse_byte The general-purpose fuse byte: 0 to 7.
Returns:
The value of the specified general-purpose fuse byte.
Note:
The actual number of general-purpose fuse bits implemented by hardware is given by AVR32_FLASHC_GPF_NUM. The other bits among the 64 are fixed at 1 by hardware.
Definition at line 446 of file flashc.c.
References flashc_read_all_gp_fuses().
Referenced by flashc_erase_gp_fuse_byte().
{
  return flashc_read_all_gp_fuses() >> ((gp_fuse_byte & 0x07) << 3);
}
void flashc_set_all_gp_fuses (U64 value)
Sets all general-purpose fuses with the appropriate erase and write operations.
Parameters:
value The value of all general-purpose fuses as a word.
Warning:
A Lock Error is issued if the Security bit is active.
Note:
The FLASHC error status returned by flashc_is_lock_error and flashc_is_programming_error is updated.
The actual number of general-purpose fuse bits implemented by hardware is given by AVR32_FLASHC_GPF_NUM. The other bits among the 64 are fixed at 1 by hardware.
Definition at line 593 of file flashc.c.
References FALSE, flashc_erase_all_gp_fuses(), flashc_error_status, and flashc_write_all_gp_fuses().
{
  unsigned int error_status;
  switch (value)
  {
  case 0xFFFFFFFFFFFFFFFFULL:
    flashc_erase_all_gp_fuses(FALSE);
    break;
  case 0x0000000000000000ULL:
    flashc_write_all_gp_fuses(0x0000000000000000ULL);
    break;
  default:
    flashc_erase_all_gp_fuses(FALSE);
    error_status = flashc_error_status;
    flashc_write_all_gp_fuses(value);
    flashc_error_status |= error_status;
  }
}
unsigned int flashc_set_bootloader_protected_size (unsigned int bootprot_size)
Sets the bootloader protected size.
Parameters:
bootprot_size The wanted bootloader protected size in bytes. If this size is not supported, the actual size will be the nearest greater available size or the maximal possible size if the requested size is too large.
Returns:
The actual bootloader protected size in bytes.
Warning:
A Lock Error is issued if the Security bit is active.
Note:
The FLASHC error status returned by flashc_is_lock_error and flashc_is_programming_error is updated.
Definition at line 361 of file flashc.c.
References flashc_get_bootloader_protected_size(), and flashc_set_gp_fuse_bitfield().
{
  flashc_set_gp_fuse_bitfield(AVR32_FLASHC_FGPFRLO_BOOTPROT_OFFSET,
                              AVR32_FLASHC_FGPFRLO_BOOTPROT_SIZE,
                              (1 << AVR32_FLASHC_FGPFRLO_BOOTPROT_SIZE) - 1 -
                              ((bootprot_size) ?
                               32 - clz((((min(max(bootprot_size, AVR32_FLASHC_PAGE_SIZE << 1),
                                               AVR32_FLASHC_PAGE_SIZE <<
                                               ((1 << AVR32_FLASHC_FGPFRLO_BOOTPROT_SIZE) - 1)) +
                                           AVR32_FLASHC_PAGE_SIZE - 1) /
                                          AVR32_FLASHC_PAGE_SIZE) << 1) - 1) - 1 :
                               0));
  return flashc_get_bootloader_protected_size();
}
void flashc_set_bus_freq (unsigned int cpu_f_hz)
Depending on the CPU frequency, set the wait states of flash read accesses.
Parameters:
cpu_f_hz The CPU frequency
Definition at line 163 of file flashc.c.
References flashc_set_wait_state().
{
  if(cpu_f_hz >= AVR32_FLASHC_FWS_0_MAX_FREQ)
  {
    // Set 1 WS.
    flashc_set_wait_state(1);
  }
  else
  {
    // Set 0 WS.
    flashc_set_wait_state(0);
  }
}
void flashc_set_gp_fuse_bit (unsigned int gp_fuse_bit, Bool value)
Sets a general-purpose fuse bit with the appropriate erase and write operations.
Parameters:
gp_fuse_bit The general-purpose fuse bit: 0 to 63.
value The value of the specified general-purpose fuse bit.
Warning:
A Lock Error is issued if the Security bit is active and the command is applied to BOOTPROT or EPFL fuses.
Note:
The FLASHC error status returned by flashc_is_lock_error and flashc_is_programming_error is updated.
The actual number of general-purpose fuse bits implemented by hardware is given by AVR32_FLASHC_GPF_NUM. The other bits among the 64 are fixed at 1 by hardware.
Definition at line 549 of file flashc.c.
References FALSE, flashc_erase_gp_fuse_bit(), and flashc_write_gp_fuse_bit().
Referenced by flashc_lock_external_privileged_fetch(), and flashc_set_gp_fuse_bitfield().
{
  if (value)
    flashc_erase_gp_fuse_bit(gp_fuse_bit, FALSE);
  else
    flashc_write_gp_fuse_bit(gp_fuse_bit, FALSE);
}
void flashc_set_gp_fuse_bitfield (unsigned int pos, unsigned int width, U64 value)
Sets a general-purpose fuse bit-field with the appropriate erase and write operations.
Parameters:
pos The bit-position of the general-purpose fuse bit-field: 0 to 63.
width The bit-width of the general-purpose fuse bit-field: 0 to 64.
value The value of the specified general-purpose fuse bit-field.
Warning:
A Lock Error is issued if the Security bit is active and the command is applied to BOOTPROT or EPFL fuses.
Note:
The FLASHC error status returned by flashc_is_lock_error and flashc_is_programming_error is updated.
The actual number of general-purpose fuse bits implemented by hardware is given by AVR32_FLASHC_GPF_NUM. The other bits among the 64 are fixed at 1 by hardware.
Definition at line 558 of file flashc.c.
References flashc_error_status, and flashc_set_gp_fuse_bit().
Referenced by flashc_set_bootloader_protected_size().
{
  unsigned int error_status = 0;
  unsigned int gp_fuse_bit;
  pos &= 0x3F;
  width = min(width, 64);
  for (gp_fuse_bit = pos; gp_fuse_bit < pos + width; gp_fuse_bit++, value >>= 1)
  {
    flashc_set_gp_fuse_bit(gp_fuse_bit, value & 0x01);
    error_status |= flashc_error_status;
  }
  flashc_error_status = error_status;
}
void flashc_set_gp_fuse_byte (unsigned int gp_fuse_byte, U8 value)
Sets a general-purpose fuse byte with the appropriate erase and write operations.
Parameters:
gp_fuse_byte The general-purpose fuse byte: 0 to 7.
value The value of the specified general-purpose fuse byte.
Warning:
A Lock Error is issued if the Security bit is active.
Note:
The FLASHC error status returned by flashc_is_lock_error and flashc_is_programming_error is updated.
The actual number of general-purpose fuse bits implemented by hardware is given by AVR32_FLASHC_GPF_NUM. The other bits among the 64 are fixed at 1 by hardware.
Definition at line 573 of file flashc.c.
References FALSE, flashc_erase_gp_fuse_byte(), flashc_error_status, and flashc_write_gp_fuse_byte().
{
  unsigned int error_status;
  switch (value)
  {
  case 0xFF:
    flashc_erase_gp_fuse_byte(gp_fuse_byte, FALSE);
    break;
  case 0x00:
    flashc_write_gp_fuse_byte(gp_fuse_byte, 0x00);
    break;
  default:
    flashc_erase_gp_fuse_byte(gp_fuse_byte, FALSE);
    error_status = flashc_error_status;
    flashc_write_gp_fuse_byte(gp_fuse_byte, value);
    flashc_error_status |= error_status;
  }
}
void flashc_set_wait_state (unsigned int wait_state)
Sets the number of wait states of flash read accesses.
Parameters:
wait_state The number of wait states of flash read accesses: 0 to 1.
Definition at line 155 of file flashc.c.
References u_avr32_flashc_fcr_t::fcr, and u_avr32_flashc_fcr_t::FCR.
Referenced by flashc_set_bus_freq().
{
  u_avr32_flashc_fcr_t u_avr32_flashc_fcr = {AVR32_FLASHC.fcr};
  u_avr32_flashc_fcr.FCR.fws = wait_state;
  AVR32_FLASHC.fcr = u_avr32_flashc_fcr.fcr;
}
void flashc_write_all_gp_fuses (U64 value)
Writes all general-purpose fuses.
Parameters:
value The value of all general-purpose fuses as a word.
Warning:
A Lock Error is issued if the Security bit is active.
Note:
The FLASHC error status returned by flashc_is_lock_error and flashc_is_programming_error is updated.
A write operation can only clear bits.
The actual number of general-purpose fuse bits implemented by hardware is given by AVR32_FLASHC_GPF_NUM. The other bits among the 64 are fixed at 1 by hardware.
Definition at line 536 of file flashc.c.
References flashc_error_status, and flashc_write_gp_fuse_byte().
Referenced by flashc_set_all_gp_fuses().
{
  unsigned int error_status = 0;
  unsigned int gp_fuse_byte;
  for (gp_fuse_byte = 0; gp_fuse_byte < 8; gp_fuse_byte++, value >>= 8)
  {
    flashc_write_gp_fuse_byte(gp_fuse_byte, value);
    error_status |= flashc_error_status;
  }
  flashc_error_status = error_status;
}
void flashc_write_gp_fuse_bit (unsigned int gp_fuse_bit, Bool value)
Writes a general-purpose fuse bit.
Parameters:
gp_fuse_bit The general-purpose fuse bit: 0 to 63.
value The value of the specified general-purpose fuse bit.
Warning:
A Lock Error is issued if the Security bit is active and the command is applied to BOOTPROT or EPFL fuses.
Note:
The FLASHC error status returned by flashc_is_lock_error and flashc_is_programming_error is updated.
A write operation can only clear bits.
The actual number of general-purpose fuse bits implemented by hardware is given by AVR32_FLASHC_GPF_NUM. The other bits among the 64 are fixed at 1 by hardware.
Definition at line 508 of file flashc.c.
References flashc_issue_command().
Referenced by flashc_set_gp_fuse_bit(), and flashc_write_gp_fuse_bitfield().
{
  if (!value)
    flashc_issue_command(AVR32_FLASHC_FCMD_CMD_WGPB, gp_fuse_bit & 0x3F);
}
void flashc_write_gp_fuse_bitfield (unsigned int pos, unsigned int width, U64 value)
Writes a general-purpose fuse bit-field.
Parameters:
pos The bit-position of the general-purpose fuse bit-field: 0 to 63.
width The bit-width of the general-purpose fuse bit-field: 0 to 64.
value The value of the specified general-purpose fuse bit-field.
Warning:
A Lock Error is issued if the Security bit is active and the command is applied to BOOTPROT or EPFL fuses.
Note:
The FLASHC error status returned by flashc_is_lock_error and flashc_is_programming_error is updated.
A write operation can only clear bits.
The actual number of general-purpose fuse bits implemented by hardware is given by AVR32_FLASHC_GPF_NUM. The other bits among the 64 are fixed at 1 by hardware.
Definition at line 515 of file flashc.c.
References flashc_error_status, and flashc_write_gp_fuse_bit().
{
  unsigned int error_status = 0;
  unsigned int gp_fuse_bit;
  pos &= 0x3F;
  width = min(width, 64);
  for (gp_fuse_bit = pos; gp_fuse_bit < pos + width; gp_fuse_bit++, value >>= 1)
  {
    flashc_write_gp_fuse_bit(gp_fuse_bit, value & 0x01);
    error_status |= flashc_error_status;
  }
  flashc_error_status = error_status;
}
void flashc_write_gp_fuse_byte (unsigned int gp_fuse_byte, U8 value)
Writes a general-purpose fuse byte.
Parameters:
gp_fuse_byte The general-purpose fuse byte: 0 to 7.
value The value of the specified general-purpose fuse byte.
Warning:
A Lock Error is issued if the Security bit is active.
Note:
The FLASHC error status returned by flashc_is_lock_error and flashc_is_programming_error is updated.
A write operation can only clear bits.
The actual number of general-purpose fuse bits implemented by hardware is given by AVR32_FLASHC_GPF_NUM. The other bits among the 64 are fixed at 1 by hardware.
Definition at line 530 of file flashc.c.
References flashc_issue_command().
Referenced by flashc_erase_gp_fuse_byte(), flashc_set_gp_fuse_byte(), and flashc_write_all_gp_fuses().
{
  flashc_issue_command(AVR32_FLASHC_FCMD_CMD_PGPFB, (gp_fuse_byte & 0x07) | value << 3);
}
void flashc_write_page (int page_number)
Writes a page from the page buffer.
Parameters:
page_number The page number:
0 to (flashc_get_page_count() - 1): a page number within the flash array;
< 0: the current page number.
Warning:
A Lock Error is issued if the command is applied to a page belonging to a locked region or to the bootloader protected area.
The page buffer is not automatically reset after a page write.
Note:
The FLASHC error status returned by flashc_is_lock_error and flashc_is_programming_error is updated.
A write operation can only clear bits.
Definition at line 669 of file flashc.c.
References flashc_issue_command().
Referenced by flashc_memcpy(), and flashc_memset64().
{
  flashc_issue_command(AVR32_FLASHC_FCMD_CMD_WP, page_number);
}
void flashc_write_user_page (void)
Writes the User page from the page buffer.
Warning:
The page buffer is not automatically reset after a page write.
Note:
The FLASHC error status returned by flashc_is_lock_error and flashc_is_programming_error is updated.
A write operation can only clear bits.
Definition at line 689 of file flashc.c.
References flashc_issue_command().
Referenced by flashc_memcpy(), and flashc_memset64().
{
  flashc_issue_command(AVR32_FLASHC_FCMD_CMD_WUP, -1);
}
Variable Documentation
void(*volatile flashc_wait_until_ready)(void)
Pointer to the function used by the driver when it needs to wait until the FLASHC is ready to run a new command.
The default function is flashc_default_wait_until_ready. The user may change this pointer to use another implementation.
Definition at line 239 of file flashc.c.
Referenced by flashc_issue_command().