PWM4 Example for uc3c_ek: scif_uc3c.h File Reference
scif_uc3c.h File Reference
System Control InterFace(SCIF) driver interface.
#include "compiler.h"
Data Structures
struct scif_gclk_opt_t
Generic clock generation settings.
struct scif_osc32_opt_t
OSC32 startup options.
struct scif_osc_opt_t
OSC0/OSC1 startup options.
struct scif_pll_opt_t
PLL0/PLL1 startup options.
Defines
#define SCIF_EXT_CRYSTAL_MAX_FREQ_HZ 20000000
#define SCIF_EXT_CRYSTAL_MIN_FREQ_HZ 4000000
Device-specific data.
#define SCIF_NOT_SUPPORTED (-10000)
Define "not supported" for the chosen implementation.
#define SCIF_POLL_TIMEOUT 100000
The timeguard used for polling in ticks.
#define SCIF_UNLOCK(reg) (AVR32_SCIF.unlock = (AVR32_SCIF_UNLOCK_KEY_VALUE << AVR32_SCIF_UNLOCK_KEY_OFFSET)|(reg))
Unlock SCIF register macro.
Enumerations
enum scif_gcctrl_oscsel_t {
SCIF_GCCTRL_SLOWCLOCK = AVR32_SCIF_GC_USES_CLK_SLOW,
SCIF_GCCTRL_OSC32K = AVR32_SCIF_GC_USES_CLK_32,
SCIF_GCCTRL_OSC0 = AVR32_SCIF_GC_USES_OSC0,
SCIF_GCCTRL_OSC1 = AVR32_SCIF_GC_USES_OSC1,
SCIF_GCCTRL_PLL0 = AVR32_SCIF_GC_USES_PLL0,
SCIF_GCCTRL_PLL1 = AVR32_SCIF_GC_USES_PLL1,
SCIF_GCCTRL_RC8M = AVR32_SCIF_GC_USES_RCOSC8,
SCIF_GCCTRL_CPUCLOCK = AVR32_SCIF_GC_USES_CLK_CPU,
SCIF_GCCTRL_HSBCLOCK = AVR32_SCIF_GC_USES_CLK_HSB,
SCIF_GCCTRL_PBACLOCK = AVR32_SCIF_GC_USES_CLK_PBA,
SCIF_GCCTRL_PBBCLOCK = AVR32_SCIF_GC_USES_CLK_PBB,
SCIF_GCCTRL_OSCSEL_INVALID
}
The different clock source for the generic clocks.
enum scif_osc_mode_t {
SCIF_OSC_MODE_EXT_CLK = 0,
SCIF_OSC_MODE_2PIN_CRYSTAL = 1,
SCIF_OSC_MODE_2PIN_CRYSTAL_HICUR = 2
}
The different oscillator modes.
enum scif_osc_t {
SCIF_OSC0 = 0,
SCIF_OSC1 = 1
}
The different oscillators.
enum scif_pll_t {
SCIF_PLL0 = 0,
SCIF_PLL1 = 1
}
The different plls.
Functions
Calibration Functions
void scif_bod18_clear_irq (void)
Clears the 1.8V Brown-Out Detector interrupt flag.
void scif_bod18_disable_irq (void)
Disables the 1.8V Brown-Out Detector interrupt.
void scif_bod18_enable_irq (void)
Enables the 1.8V Brown-Out Detector interrupt.
unsigned long scif_bod18_get_irq_enable_bit (void)
Gets the 1.8V Brown-Out Detector interrupt enable status.
unsigned long scif_bod18_get_irq_status (void)
Gets the 1.8V Brown-Out Detector interrupt flag.
unsigned long scif_bod18_get_level (void)
Gets the triggering threshold of the 1.8V Brown-Out Detector.
void scif_bod33_clear_irq (void)
Clears the 3.3V Brown-Out Detector interrupt flag.
void scif_bod33_disable_irq (void)
Disables the 3.3V Brown-Out Detector interrupt.
void scif_bod33_enable_irq (void)
Enables the 3.3V Brown-Out Detector interrupt.
unsigned long scif_bod33_get_irq_enable_bit (void)
Gets the 3.3V Brown-Out Detector interrupt enable status.
unsigned long scif_bod33_get_irq_status (void)
Gets the 3.3V Brown-Out Detector interrupt flag.
unsigned long scif_bod33_get_level (void)
Gets the triggering threshold of the 3.3V Brown-Out Detector.
void scif_bod50_clear_irq (void)
Clears the 5.0V Brown-Out Detector interrupt flag.
void scif_bod50_disable_irq (void)
Disables the 5.0V Brown-Out Detector interrupt.
void scif_bod50_enable_irq (void)
Enables the 5.0V Brown-Out Detector interrupt.
unsigned long scif_bod50_get_irq_enable_bit (void)
Gets the 5.0V Brown-Out Detector interrupt enable status.
unsigned long scif_bod50_get_irq_status (void)
Gets the 5.0V Brown-Out Detector interrupt flag.
unsigned long scif_bod50_get_level (void)
Gets the triggering threshold of the 5.0V Brown-Out Detector.
Interrupt Functions
static void scif_clear_interrupts_status (unsigned long mask)
Clear raised interrupts from the SCIF.
static void scif_disable_interrupts (unsigned long mask)
Disable SCIF interrupts.
static void scif_enable_interrupts (unsigned long mask)
Enable SCIF interrupts.
static unsigned long scif_get_enabled_interrupts (void)
Read the SCIF currently enabled interrupts.
static unsigned long scif_get_interrupts_status (void)
Read the interrupt status of the SCIF.
OSC0/OSC1 Functions
long int scif_configure_osc_crystalmode (scif_osc_t osc, unsigned int fcrystal)
Configure an oscillator in crystal mode.
long int scif_configure_osc_extmode (scif_osc_t osc)
Configure an external clock as input clock.
long int scif_enable_extosc (scif_osc_t osc)
Enable external clock.
long int scif_enable_osc (scif_osc_t osc, unsigned int startup, bool wait_for_ready)
Enable an oscillator with a given startup time.
bool scif_is_osc_ready (scif_osc_t osc)
Is an oscillator stable and ready to be used as clock source?
long int scif_start_osc (scif_osc_t osc, const scif_osc_opt_t *opt, bool wait_for_ready)
Configure and start an OSC0/OSC1 oscillator.
long int scif_stop_osc (scif_osc_t osc)
Stop an oscillator.
Generic Clock Functions
long int scif_gc_enable (unsigned int gclk)
Enable a generic clock.
long int scif_gc_setup (unsigned int gclk, scif_gcctrl_oscsel_t clk_src, unsigned int diven, unsigned int divfactor)
Setup a generic clock.
long int scif_start_gclk (unsigned int gclk, const scif_gclk_opt_t *opt)
Setup and start a generic clock.
long int scif_stop_gclk (unsigned int gclk)
Stop a generic clock.
Power and Clocks Status Functions
static unsigned long scif_get_pclk_status (void)
Read the Power and Clocks Status of the SCIF.
OSC32 Functions
static bool scif_is_osc32_ready (void)
Is OSC32 stable and ready to be used as clock source?
long int scif_start_osc32 (const scif_osc32_opt_t *opt, bool wait_for_ready)
Configure and start the OSC32 oscillator.
long int scif_stop_osc32 (void)
Stop the OSC32 oscillator.
PLL0/PLL1 Functions
long int scif_pll_disable (scif_pll_t pll)
This function will disable a PLL.
long int scif_pll_enable (scif_pll_t pll)
This function will enable a PLL.
long int scif_pll_setup (scif_pll_t pll, const scif_pll_opt_t opt)
This function will setup a PLL.
long int scif_wait_for_pll_locked (scif_pll_t pll)
This function will wait for PLL locked.
Backup Registers Functions
unsigned long scif_read_gplp (unsigned long gplp)
Read the content of the SCIF GPLP registers.
void scif_write_gplp (int gplp, unsigned long value)
Write into the SCIF GPLP registers.
120MHz RCosc Functions
void scif_start_rc120M (void)
Start the 120MHz internal RCosc (RC120M) clock.
void scif_stop_rc120M (void)
Stop the 120MHz internal RCosc (RC120M) clock.
8MHz RCosc Functions
void scif_start_rc8M (void)
Start the 8MHz internal RCosc (RC8M) clock.
void scif_stop_rc8M (void)
Stop the 8MHz internal RCosc (RC8M) clock.
Temperature Sensor Management Functions
static void scif_temperature_sensor_disable (void)
Disable the temperature sensor.
static void scif_temperature_sensor_enable (void)
Enable the temperature sensor.
Detailed Description
System Control InterFace(SCIF) driver interface.
Compiler: IAR EWAVR32 and GNU GCC for AVR32
Supported devices: All AVR32 UC3C devices.
AppNote:
Author:
Atmel Corporation: http://www.atmel.com
Support and FAQ: http://support.atmel.no/
Definition in file scif_uc3c.h.
Define Documentation
#define SCIF_EXT_CRYSTAL_MAX_FREQ_HZ 20000000
Definition at line 103 of file scif_uc3c.h.
Referenced by scif_start_osc(), and scif_start_osc32().
#define SCIF_EXT_CRYSTAL_MIN_FREQ_HZ 4000000
Device-specific data.
< External crystal/clock min frequency (in Herz) External crystal/clock max frequency (in Herz)
Definition at line 101 of file scif_uc3c.h.
Referenced by scif_start_osc(), and scif_start_osc32().
#define SCIF_NOT_SUPPORTED (-10000)
Define "not supported" for the chosen implementation.
Definition at line 128 of file scif_uc3c.h.
#define SCIF_POLL_TIMEOUT 100000
The timeguard used for polling in ticks.
Definition at line 125 of file scif_uc3c.h.
Referenced by scif_pclksr_statushigh_wait(), and scif_stop_gclk().
#define SCIF_UNLOCK (reg) (AVR32_SCIF.unlock = (AVR32_SCIF_UNLOCK_KEY_VALUE << AVR32_SCIF_UNLOCK_KEY_OFFSET)|(reg))
Unlock SCIF register macro.
Definition at line 210 of file scif_uc3c.h.
Referenced by scif_configure_osc_crystalmode(), scif_configure_osc_extmode(), scif_enable_extosc(), scif_enable_osc(), scif_pll_disable(), scif_pll_enable(), scif_pll_setup(), scif_start_osc(), scif_start_osc32(), scif_start_rc120M(), scif_start_rc8M(), scif_stop_osc(), scif_stop_osc32(), scif_stop_rc120M(), scif_stop_rc8M(), scif_temperature_sensor_disable(), scif_temperature_sensor_enable(), and scif_write_gplp().
Enumeration Type Documentation
enum scif_gcctrl_oscsel_t
The different clock source for the generic clocks.
Enumerator:
SCIF_GCCTRL_SLOWCLOCK
SCIF_GCCTRL_OSC32K
SCIF_GCCTRL_OSC0
SCIF_GCCTRL_OSC1
SCIF_GCCTRL_PLL0
SCIF_GCCTRL_PLL1
SCIF_GCCTRL_RC8M
SCIF_GCCTRL_CPUCLOCK
SCIF_GCCTRL_HSBCLOCK
SCIF_GCCTRL_PBACLOCK
SCIF_GCCTRL_PBBCLOCK
SCIF_GCCTRL_OSCSEL_INVALID
Definition at line 106 of file scif_uc3c.h.
{
  SCIF_GCCTRL_SLOWCLOCK  = AVR32_SCIF_GC_USES_CLK_SLOW,
  SCIF_GCCTRL_OSC32K  = AVR32_SCIF_GC_USES_CLK_32,
  SCIF_GCCTRL_OSC0  = AVR32_SCIF_GC_USES_OSC0,
  SCIF_GCCTRL_OSC1  = AVR32_SCIF_GC_USES_OSC1,
  SCIF_GCCTRL_PLL0  = AVR32_SCIF_GC_USES_PLL0,
  SCIF_GCCTRL_PLL1  = AVR32_SCIF_GC_USES_PLL1,
  SCIF_GCCTRL_RC8M  = AVR32_SCIF_GC_USES_RCOSC8,
  SCIF_GCCTRL_CPUCLOCK  = AVR32_SCIF_GC_USES_CLK_CPU,
  SCIF_GCCTRL_HSBCLOCK  = AVR32_SCIF_GC_USES_CLK_HSB,
  SCIF_GCCTRL_PBACLOCK  = AVR32_SCIF_GC_USES_CLK_PBA,
  SCIF_GCCTRL_PBBCLOCK  = AVR32_SCIF_GC_USES_CLK_PBB,
  SCIF_GCCTRL_OSCSEL_INVALID
} scif_gcctrl_oscsel_t;
enum scif_osc_mode_t
The different oscillator modes.
Enumerator:
SCIF_OSC_MODE_EXT_CLK
SCIF_OSC_MODE_2PIN_CRYSTAL
SCIF_OSC_MODE_2PIN_CRYSTAL_HICUR
Definition at line 146 of file scif_uc3c.h.
{
  SCIF_OSC_MODE_EXT_CLK = 0,            // For both OSC0 & OSC32
  SCIF_OSC_MODE_2PIN_CRYSTAL = 1,       // For both OSC0 & OSC32
  SCIF_OSC_MODE_2PIN_CRYSTAL_HICUR = 2, // For OSC32 only
} scif_osc_mode_t;
enum scif_osc_t
The different oscillators.
Enumerator:
SCIF_OSC0
SCIF_OSC1
Definition at line 132 of file scif_uc3c.h.
{
  SCIF_OSC0  = 0,
  SCIF_OSC1  = 1
} scif_osc_t;
enum scif_pll_t
The different plls.
Enumerator:
SCIF_PLL0
SCIF_PLL1
Definition at line 139 of file scif_uc3c.h.
{
  SCIF_PLL0  = 0,
  SCIF_PLL1  = 1
} scif_pll_t;
Function Documentation
void scif_bod18_clear_irq (void)
Clears the 1.8V Brown-Out Detector interrupt flag.
Definition at line 695 of file scif_uc3c.c.
{
  AVR32_SCIF.icr = AVR32_SCIF_ICR_BODDET_MASK;
}
void scif_bod18_disable_irq (void)
Disables the 1.8V Brown-Out Detector interrupt.
Definition at line 685 of file scif_uc3c.c.
References Disable_global_interrupt, Enable_global_interrupt, and Is_global_interrupt_enabled.
{
  Bool global_interrupt_enabled = Is_global_interrupt_enabled();
  if (global_interrupt_enabled) Disable_global_interrupt();
  AVR32_SCIF.idr = AVR32_SCIF_IDR_BODDET_MASK;
  AVR32_SCIF.isr;
  if (global_interrupt_enabled) Enable_global_interrupt();
}
void scif_bod18_enable_irq (void)
Enables the 1.8V Brown-Out Detector interrupt.
Definition at line 680 of file scif_uc3c.c.
{
  AVR32_SCIF.ier = AVR32_SCIF_IER_BODDET_MASK ;
}
unsigned long scif_bod18_get_irq_enable_bit (void)
Gets the 1.8V Brown-Out Detector interrupt enable status.
Return values:
0 BOD interrupt disabled.
1 BOD interrupt enabled.
Definition at line 705 of file scif_uc3c.c.
{
  return ((AVR32_SCIF.imr & AVR32_SCIF_IMR_BODDET_MASK) != 0);
}
unsigned long scif_bod18_get_irq_status (void)
Gets the 1.8V Brown-Out Detector interrupt flag.
Return values:
0 No BOD interrupt.
1 BOD interrupt pending.
Definition at line 700 of file scif_uc3c.c.
{
  return ((AVR32_SCIF.isr & AVR32_SCIF_ISR_BODDET_MASK) != 0);
}
unsigned long scif_bod18_get_level (void)
Gets the triggering threshold of the 1.8V Brown-Out Detector.
Definition at line 710 of file scif_uc3c.c.
{
  return (AVR32_SCIF.bod & AVR32_SCIF_BOD_LEVEL_MASK) >> AVR32_SCIF_BOD_LEVEL_OFFSET;
}
void scif_bod33_clear_irq (void)
Clears the 3.3V Brown-Out Detector interrupt flag.
Definition at line 730 of file scif_uc3c.c.
{
  AVR32_SCIF.icr = AVR32_SCIF_ICR_BOD33DET_MASK;
}
void scif_bod33_disable_irq (void)
Disables the 3.3V Brown-Out Detector interrupt.
Definition at line 720 of file scif_uc3c.c.
References Disable_global_interrupt, Enable_global_interrupt, and Is_global_interrupt_enabled.
{
   Bool global_interrupt_enabled = Is_global_interrupt_enabled();
  if (global_interrupt_enabled) Disable_global_interrupt();
  AVR32_SCIF.idr = AVR32_SCIF_IDR_BOD33DET_MASK;
  AVR32_SCIF.isr;
  if (global_interrupt_enabled) Enable_global_interrupt();
}
void scif_bod33_enable_irq (void)
Enables the 3.3V Brown-Out Detector interrupt.
Definition at line 715 of file scif_uc3c.c.
{
  AVR32_SCIF.ier = AVR32_SCIF_IER_BOD33DET_MASK ;
}
unsigned long scif_bod33_get_irq_enable_bit (void)
Gets the 3.3V Brown-Out Detector interrupt enable status.
Return values:
0 BOD interrupt disabled.
1 BOD interrupt enabled.
Definition at line 740 of file scif_uc3c.c.
{
  return ((AVR32_SCIF.imr & AVR32_SCIF_IMR_BOD33DET_MASK) != 0);
}
unsigned long scif_bod33_get_irq_status (void)
Gets the 3.3V Brown-Out Detector interrupt flag.
Return values:
0 No BOD interrupt.
1 BOD interrupt pending.
Definition at line 735 of file scif_uc3c.c.
{
  return ((AVR32_SCIF.isr & AVR32_SCIF_ISR_BOD33DET_MASK) != 0);
}
unsigned long scif_bod33_get_level (void)
Gets the triggering threshold of the 3.3V Brown-Out Detector.
Definition at line 745 of file scif_uc3c.c.
{
  return (AVR32_SCIF.bod33 & AVR32_SCIF_BOD33_LEVEL_MASK) >> AVR32_SCIF_BOD33_LEVEL_OFFSET;
}
void scif_bod50_clear_irq (void)
Clears the 5.0V Brown-Out Detector interrupt flag.
Definition at line 765 of file scif_uc3c.c.
{
  AVR32_SCIF.icr = AVR32_SCIF_ICR_BOD50DET_MASK;
}
void scif_bod50_disable_irq (void)
Disables the 5.0V Brown-Out Detector interrupt.
Definition at line 755 of file scif_uc3c.c.
References Disable_global_interrupt, Enable_global_interrupt, and Is_global_interrupt_enabled.
{
   Bool global_interrupt_enabled = Is_global_interrupt_enabled();
  if (global_interrupt_enabled) Disable_global_interrupt();
  AVR32_SCIF.idr = AVR32_SCIF_IDR_BOD50DET_MASK;
  AVR32_SCIF.isr;
  if (global_interrupt_enabled) Enable_global_interrupt();
}
void scif_bod50_enable_irq (void)
Enables the 5.0V Brown-Out Detector interrupt.
Definition at line 750 of file scif_uc3c.c.
{
  AVR32_SCIF.ier = AVR32_SCIF_IER_BOD50DET_MASK ;
}
unsigned long scif_bod50_get_irq_enable_bit (void)
Gets the 5.0V Brown-Out Detector interrupt enable status.
Return values:
0 BOD interrupt disabled.
1 BOD interrupt enabled.
Definition at line 775 of file scif_uc3c.c.
{
  return ((AVR32_SCIF.imr & AVR32_SCIF_IMR_BOD50DET_MASK) != 0);
}
unsigned long scif_bod50_get_irq_status (void)
Gets the 5.0V Brown-Out Detector interrupt flag.
Return values:
0 No BOD interrupt.
1 BOD interrupt pending.
Definition at line 770 of file scif_uc3c.c.
{
  return ((AVR32_SCIF.isr & AVR32_SCIF_ISR_BOD50DET_MASK) != 0);
}
unsigned long scif_bod50_get_level (void)
Gets the triggering threshold of the 5.0V Brown-Out Detector.
Definition at line 780 of file scif_uc3c.c.
{
  return (AVR32_SCIF.bod50 & AVR32_SCIF_BOD50_LEVEL_MASK) >> AVR32_SCIF_BOD50_LEVEL_OFFSET;
}
static void scif_clear_interrupts_status (unsigned long mask) [inline, static]
Clear raised interrupts from the SCIF.
Parameters:
mask The interrupts to clear.
Definition at line 271 of file scif_uc3c.h.
{
  AVR32_SCIF.icr = mask;
}
long int scif_configure_osc_crystalmode (scif_osc_t osc, unsigned int fcrystal)
Configure an oscillator in crystal mode.
Parameters:
osc The oscillator to configure [INPUT]
fcrystal Crystal frequency (Hz) [INPUT]
Returns:
Status.
Return values:
0 Oscillator successfully configured.
<0 Error configuring the oscillator.
Definition at line 228 of file scif_uc3c.c.
References AVR32_ENTER_CRITICAL_REGION, AVR32_LEAVE_CRITICAL_REGION, u_avr32_scif_oscctrl_t::OSCCTRL, PASS, SCIF_OSC0, SCIF_OSC1, SCIF_OSC_MODE_2PIN_CRYSTAL, and SCIF_UNLOCK.
Referenced by pcl_configure_clocks_osc0(), and pcl_switch_to_osc().
{
  u_avr32_scif_oscctrl_t   u_avr32_scif_oscctrl;
  if (osc == SCIF_OSC0)
  {
    // Read Register
    u_avr32_scif_oscctrl.OSCCTRL[SCIF_OSC0] = AVR32_SCIF.OSCCTRL[SCIF_OSC0] ;
    // Modify : Configure the oscillator mode to crystal and set the gain according to the
    // cyrstal frequency.
    u_avr32_scif_oscctrl.OSCCTRL[SCIF_OSC0].mode = SCIF_OSC_MODE_2PIN_CRYSTAL;
    u_avr32_scif_oscctrl.OSCCTRL[SCIF_OSC0].gain = (fcrystal <  900000) ? AVR32_SCIF_OSCCTRL0_GAIN_G0 :
                                                   (fcrystal < 3000000) ? AVR32_SCIF_OSCCTRL0_GAIN_G1 :
                                                   (fcrystal < 8000000) ? AVR32_SCIF_OSCCTRL0_GAIN_G2 :
                                                                          AVR32_SCIF_OSCCTRL0_GAIN_G3;
    AVR32_ENTER_CRITICAL_REGION( );
    // Unlock the write-protected OSCCTRL0 register
    SCIF_UNLOCK(AVR32_SCIF_OSCCTRL);
    // Write Back
    AVR32_SCIF.OSCCTRL[SCIF_OSC0] = u_avr32_scif_oscctrl.OSCCTRL[SCIF_OSC0];
    AVR32_LEAVE_CRITICAL_REGION( );
  }
  else
  {
    // Read Register
    u_avr32_scif_oscctrl.OSCCTRL[SCIF_OSC1] = AVR32_SCIF.OSCCTRL[SCIF_OSC1] ;
    // Modify : Configure the oscillator mode to crystal and set the gain according to the
    // cyrstal frequency.
    u_avr32_scif_oscctrl.OSCCTRL[SCIF_OSC1].mode = SCIF_OSC_MODE_2PIN_CRYSTAL;
    u_avr32_scif_oscctrl.OSCCTRL[SCIF_OSC1].gain = (fcrystal <  900000) ? AVR32_SCIF_OSCCTRL1_GAIN_G0 :
                                                   (fcrystal < 3000000) ? AVR32_SCIF_OSCCTRL1_GAIN_G1 :
                                                   (fcrystal < 8000000) ? AVR32_SCIF_OSCCTRL1_GAIN_G2 :
                                                                          AVR32_SCIF_OSCCTRL1_GAIN_G3;
    AVR32_ENTER_CRITICAL_REGION( );
    // Unlock the write-protected OSCCTRL1 register
    SCIF_UNLOCK(AVR32_SCIF_OSCCTRL + 4);
    // Write Back
    AVR32_SCIF.OSCCTRL[SCIF_OSC1] = u_avr32_scif_oscctrl.OSCCTRL[SCIF_OSC1];
    AVR32_LEAVE_CRITICAL_REGION( );
  }
  return PASS;
}
long int scif_configure_osc_extmode (scif_osc_t osc)
Configure an external clock as input clock.
Parameters:
osc The external clock to configure [INPUT]
Returns:
Status.
Return values:
0 External clock successfully configured.
<0 Error configuring the external clock.
Definition at line 272 of file scif_uc3c.c.
References AVR32_ENTER_CRITICAL_REGION, AVR32_LEAVE_CRITICAL_REGION, u_avr32_scif_oscctrl_t::OSCCTRL, PASS, SCIF_OSC_MODE_EXT_CLK, and SCIF_UNLOCK.
{
  u_avr32_scif_oscctrl_t   u_avr32_scif_oscctrl;
      // Read Register
    u_avr32_scif_oscctrl.OSCCTRL[osc] = AVR32_SCIF.OSCCTRL[osc] ;
    // Modify : Configure the oscillator mode to crystal and set the gain according to the
    // cyrstal frequency.
    u_avr32_scif_oscctrl.OSCCTRL[osc].mode = SCIF_OSC_MODE_EXT_CLK;
    AVR32_ENTER_CRITICAL_REGION( );
    // Unlock the write-protected OSCCTRL0 register
    SCIF_UNLOCK(AVR32_SCIF_OSCCTRL + 4*osc);
    // Write Back
    AVR32_SCIF.OSCCTRL[osc] = u_avr32_scif_oscctrl.OSCCTRL[osc];
    AVR32_LEAVE_CRITICAL_REGION( );
  return PASS;
}
static void scif_disable_interrupts (unsigned long mask) [inline, static]
Disable SCIF interrupts.
Parameters:
mask the interrupts to disable.
Definition at line 235 of file scif_uc3c.h.
{
  AVR32_SCIF.idr = mask;
}
long int scif_enable_extosc (scif_osc_t osc)
Enable external clock.
Parameters:
osc The oscillator to configure [INPUT]
Returns:
Status.
Return values:
0 Oscillator successfully started
<0 Error starting the oscillator.
Definition at line 318 of file scif_uc3c.c.
References AVR32_ENTER_CRITICAL_REGION, AVR32_LEAVE_CRITICAL_REGION, ENABLE, u_avr32_scif_oscctrl_t::OSCCTRL, PASS, and SCIF_UNLOCK.
{
  u_avr32_scif_oscctrl_t   u_avr32_scif_oscctrl;
  // Read Register
  u_avr32_scif_oscctrl.OSCCTRL[osc] = AVR32_SCIF.OSCCTRL[osc] ;
  // Modify : Enable the osc.
  u_avr32_scif_oscctrl.OSCCTRL[osc].oscen = ENABLE;
  AVR32_ENTER_CRITICAL_REGION( );
  // Unlock the write-protected OSCCTRL0 register
  SCIF_UNLOCK(AVR32_SCIF_OSCCTRL + 4*osc);
  // Write Back
  AVR32_SCIF.OSCCTRL[osc] = u_avr32_scif_oscctrl.OSCCTRL[osc];
  AVR32_LEAVE_CRITICAL_REGION( );
  return PASS;
}
static void scif_enable_interrupts (unsigned long mask) [inline, static]
Enable SCIF interrupts.
Parameters:
mask the interrupts to enable.
Definition at line 223 of file scif_uc3c.h.
{
  AVR32_SCIF.ier = mask;
}
long int scif_enable_osc (scif_osc_t osc, unsigned int startup, bool wait_for_ready)
Enable an oscillator with a given startup time.
Parameters:
osc The oscillator to configure [INPUT]
startup Oscillator startup time (one of AVR32_SCIF_OSCCTRLx_STARTUP_x_RCOSC) [INPUT]
wait_for_ready Wait for the oscillator to be stable before return [INPUT]
Returns:
Status.
Return values:
0 Oscillator successfully started
<0 Error starting the oscillator.
Definition at line 291 of file scif_uc3c.c.
References AVR32_ENTER_CRITICAL_REGION, AVR32_LEAVE_CRITICAL_REGION, ENABLE, u_avr32_scif_oscctrl_t::OSCCTRL, PASS, scif_pclksr_statushigh_wait(), and SCIF_UNLOCK.
Referenced by pcl_configure_clocks_osc0(), and pcl_switch_to_osc().
{
  u_avr32_scif_oscctrl_t   u_avr32_scif_oscctrl;
  // Read Register
  u_avr32_scif_oscctrl.OSCCTRL[osc] = AVR32_SCIF.OSCCTRL[osc] ;
  // Modify: Configure the oscillator startup and enable the osc.
  u_avr32_scif_oscctrl.OSCCTRL[osc].startup = startup;
  u_avr32_scif_oscctrl.OSCCTRL[osc].oscen = ENABLE;
  AVR32_ENTER_CRITICAL_REGION( );
  // Unlock the write-protected OSCCTRL0 register
  SCIF_UNLOCK(AVR32_SCIF_OSCCTRL + 4*osc);
  // Write Back
  AVR32_SCIF.OSCCTRL[osc] = u_avr32_scif_oscctrl.OSCCTRL[osc];
  AVR32_LEAVE_CRITICAL_REGION( );
  if(true == wait_for_ready)
  {
    // Wait until OSC0 is stable and ready to be used.
    if(scif_pclksr_statushigh_wait(AVR32_SCIF_PCLKSR_OSC0RDY_MASK))
      return -1;
  }
  return PASS;
}
long int scif_gc_enable (unsigned int gclk)
Enable a generic clock.
Parameters:
gclk generic clock number (0 for gc0...)
Returns:
Status.
Return values:
0 Success.
<0 An error occured.
Definition at line 662 of file scif_uc3c.c.
References PASS.
Referenced by pcl_configure_usb_clock(), and pwm_start_gc().
{
#ifdef AVR32SFW_INPUT_CHECK
  // Check that the generic clock number is correct
  if( gclk > AVR32_SCIF_GCLK_NUM )
  {
    return -1;
  }
#endif  // AVR32SFW_INPUT_CHECK
  // If the generic clock is already enabled, do nothing.
  if(!(AVR32_SCIF.gcctrl[gclk] & AVR32_SCIF_GCCTRL_CEN_MASK))
    AVR32_SCIF.gcctrl[gclk] |= AVR32_SCIF_GCCTRL_CEN_MASK;
  return PASS;
}
long int scif_gc_setup (unsigned int gclk, scif_gcctrl_oscsel_t clk_src, unsigned int diven, unsigned int divfactor)
Setup a generic clock.
Parameters:
gclk generic clock number (0 for gc0...)
clk_src The input clock source to use for the generic clock
diven Generic clock divisor enable
divfactor Generic clock divisor
Note:
If the generic clock is already enabled, this function will disable it, apply the configuration then restart the generic clock.
Returns:
Status.
Return values:
0 Success.
<0 An error occured.
Definition at line 614 of file scif_uc3c.c.
References PASS, SCIF_GCCTRL_OSCSEL_INVALID, and scif_stop_gclk().
Referenced by pcl_configure_usb_clock(), and pwm_start_gc().
{
  int restart_gc = false;
  // Change the division factor to conform to the equation: fgclk = fsrc/divfactor = fsrc/(2*(div+1))
  divfactor = (divfactor>>1) -1;
#ifdef AVR32SFW_INPUT_CHECK
  // Check that the generic clock number is correct
  if( gclk > AVR32_SCIF_GCLK_NUM )
  {
    return -1;
  }
  // Check that the clock source for the generic clock is correct.
  if(( clk_src >= SCIF_GCCTRL_OSCSEL_INVALID ) || ( clk_src < 0 ))
  {
    return -1;
  }
  // Check that the required division factor is correct.
  if(diven)
  {
    if(divfactor >= (1<<AVR32_SCIF_GCCTRL_DIV_SIZE))
      return -1;
  }
#endif  // AVR32SFW_INPUT_CHECK
  // If the generic clock is already enabled, disable it before changing its setup.
  if(AVR32_SCIF.gcctrl[gclk] & AVR32_SCIF_GCCTRL_CEN_MASK)
  {
    restart_gc = true;
    if(scif_stop_gclk(gclk) < 0)
      return -1;  // Could not stop the generic clock.
  }
  // Setup the generic clock.
  AVR32_SCIF.gcctrl[gclk] = ((divfactor << AVR32_SCIF_GCCTRL_DIV_OFFSET)&AVR32_SCIF_GCCTRL_DIV_MASK)
                            |((diven << AVR32_SCIF_GCCTRL_DIVEN_OFFSET)&AVR32_SCIF_GCCTRL_DIVEN_MASK)
                            |((clk_src << AVR32_SCIF_GCCTRL_OSCSEL_OFFSET)&AVR32_SCIF_GCCTRL_OSCSEL_MASK);
  // Restart the gc if it previously was enabled.
  if(true == restart_gc)
    AVR32_SCIF.gcctrl[gclk] |= AVR32_SCIF_GCCTRL_CEN_MASK ;
  return PASS;
}
static unsigned long scif_get_enabled_interrupts (void) [inline, static]
Read the SCIF currently enabled interrupts.
Returns:
The enabled interrupts.
Definition at line 247 of file scif_uc3c.h.
{
  return(AVR32_SCIF.imr);
}
static unsigned long scif_get_interrupts_status (void) [inline, static]
Read the interrupt status of the SCIF.
Returns:
The interrupts which have been triggered.
Definition at line 259 of file scif_uc3c.h.
{
  return(AVR32_SCIF.isr);
}
static unsigned long scif_get_pclk_status (void) [inline, static]
Read the Power and Clocks Status of the SCIF.
Returns:
The content of the PCLKSR register
Definition at line 290 of file scif_uc3c.h.
{
  return(AVR32_SCIF.pclksr);
}
static bool scif_is_osc32_ready (void) [inline, static]
Is OSC32 stable and ready to be used as clock source?
Returns:
Status.
Return values:
true oscillator stable and ready
false oscillator not enabled or not ready.
Definition at line 455 of file scif_uc3c.h.
{
  return((AVR32_SCIF.pclksr & AVR32_SCIF_PCLKSR_OSC32RDY_MASK)>>AVR32_SCIF_PCLKSR_OSC32RDY_OFFSET);
}
bool scif_is_osc_ready (scif_osc_t osc)
Is an oscillator stable and ready to be used as clock source?
Parameters:
osc The oscillator [INPUT]
Returns:
Status.
Return values:
true oscillator stable and ready
false oscillator not enabled or not ready.
Definition at line 197 of file scif_uc3c.c.
References SCIF_OSC0.
{
  if (osc == SCIF_OSC0)
  {
    return((AVR32_SCIF.pclksr & AVR32_SCIF_PCLKSR_OSC0RDY_MASK)>>AVR32_SCIF_PCLKSR_OSC0RDY_OFFSET);
  }
  else
  {
    return((AVR32_SCIF.pclksr & AVR32_SCIF_PCLKSR_OSC1RDY_MASK)>>AVR32_SCIF_PCLKSR_OSC1RDY_OFFSET);
  }
}
long int scif_pll_disable (scif_pll_t pll)
This function will disable a PLL.
Parameters:
pll The PLL to configure [INPUT]
Returns:
Status.
Return values:
0 PLL successfully started
<0 Error starting the PLL.
Definition at line 382 of file scif_uc3c.c.
References AVR32_ENTER_CRITICAL_REGION, AVR32_LEAVE_CRITICAL_REGION, DISABLE, PASS, u_avr32_scif_pll_t::PLL, and SCIF_UNLOCK.
{
  u_avr32_scif_pll_t   u_avr32_scif_pll;
  // Read Register
  u_avr32_scif_pll.PLL[pll] = AVR32_SCIF.PLL[pll] ;
  // Modify Configuration
  u_avr32_scif_pll.PLL[pll].pllen = DISABLE;
  AVR32_ENTER_CRITICAL_REGION( );
  // Unlock the write-protected PLL0 register
  SCIF_UNLOCK(AVR32_SCIF_PLL + 4*pll);
  // Write Back
  AVR32_SCIF.PLL[pll] = u_avr32_scif_pll.PLL[pll];
  AVR32_LEAVE_CRITICAL_REGION( );
  return PASS;
}
long int scif_pll_enable (scif_pll_t pll)
This function will enable a PLL.
Parameters:
pll The PLL to configure [INPUT]
Returns:
Status.
Return values:
0 PLL successfully started
<0 Error starting the PLL.
Definition at line 363 of file scif_uc3c.c.
References AVR32_ENTER_CRITICAL_REGION, AVR32_LEAVE_CRITICAL_REGION, ENABLE, PASS, u_avr32_scif_pll_t::PLL, and SCIF_UNLOCK.
Referenced by local_start_highfreq_clock(), and pcl_configure_usb_clock().
{
  u_avr32_scif_pll_t   u_avr32_scif_pll;
    // Read Register
    u_avr32_scif_pll.PLL[pll] = AVR32_SCIF.PLL[pll] ;
    // Modify Configuration
    u_avr32_scif_pll.PLL[pll].pllen = ENABLE;
    AVR32_ENTER_CRITICAL_REGION( );
    // Unlock the write-protected PLL0 register
    SCIF_UNLOCK(AVR32_SCIF_PLL + 4*pll);
    // Write Back
    AVR32_SCIF.PLL[pll] = u_avr32_scif_pll.PLL[pll];
    AVR32_LEAVE_CRITICAL_REGION( );
  return PASS;
}
long int scif_pll_setup (scif_pll_t pll, const scif_pll_opt_t opt)
This function will setup a PLL.
Parameters:
pll The PLL to configure [INPUT]
opt The configuration of the PLL [INPUT]
Returns:
Status.
Return values:
0 PLL successfully started
<0 Error starting the PLL.
Definition at line 340 of file scif_uc3c.c.
References AVR32_ENTER_CRITICAL_REGION, AVR32_LEAVE_CRITICAL_REGION, scif_pll_opt_t::div, scif_pll_opt_t::lockcount, scif_pll_opt_t::mul, scif_pll_opt_t::osc, PASS, u_avr32_scif_pll_t::PLL, scif_pll_opt_t::pll_div2, scif_pll_opt_t::pll_freq, scif_pll_opt_t::pll_wbwdisable, and SCIF_UNLOCK.
Referenced by local_start_highfreq_clock(), and pcl_configure_usb_clock().
{
  u_avr32_scif_pll_t   u_avr32_scif_pll;
  // Read Register
  u_avr32_scif_pll.PLL[pll] = AVR32_SCIF.PLL[pll] ;
  // Modify Configuration
  u_avr32_scif_pll.PLL[pll].pllosc  = opt.osc;
  u_avr32_scif_pll.PLL[pll].pllopt  = opt.pll_freq | (opt.pll_div2 << 1) | (opt.pll_wbwdisable << 2);
  u_avr32_scif_pll.PLL[pll].plldiv   = opt.div;
  u_avr32_scif_pll.PLL[pll].pllmul  = opt.mul;
  u_avr32_scif_pll.PLL[pll].pllcount= opt.lockcount;
  AVR32_ENTER_CRITICAL_REGION( );
  // Unlock the write-protected PLL0 register
  SCIF_UNLOCK(AVR32_SCIF_PLL + 4*pll);
  // Write Back
  AVR32_SCIF.PLL[pll] = u_avr32_scif_pll.PLL[pll];
  AVR32_LEAVE_CRITICAL_REGION( );
  return PASS;
}
unsigned long scif_read_gplp (unsigned long gplp)
Read the content of the SCIF GPLP registers.
Parameters:
gplp GPLP register index (0,1,... depending on the number of GPLP registers for a given part)
Returns:
The content of the chosen GPLP register.
Definition at line 100 of file scif_uc3c.c.
{
  return AVR32_SCIF.gplp[gplp];
}
long int scif_start_gclk (unsigned int gclk, const scif_gclk_opt_t * opt)
Setup and start a generic clock.
Parameters:
gclk The generic clock number to setup and start (cf. datasheet)
opt The settings for the generic clock.
Returns:
Status.
Return values:
0 Success.
<0 An error occured.
Definition at line 559 of file scif_uc3c.c.
References scif_gclk_opt_t::clock_source, scif_gclk_opt_t::diven, scif_gclk_opt_t::divider, PASS, and SCIF_GCCTRL_OSCSEL_INVALID.
{
#ifdef AVR32SFW_INPUT_CHECK
  // Check that the generic clock number is correct
  if( gclk > AVR32_SCIF_GCLK_NUM )
  {
    return -1;
  }
  // Check that the clock source for the generic clock is correct.
  if(( opt->clock_source >= SCIF_GCCTRL_OSCSEL_INVALID ) || ( opt->clock_source < 0 ))
  {
    return -1;
  }
#endif  // AVR32SFW_INPUT_CHECK
  // If the generic clock is already enabled, return an error.
  if(AVR32_SCIF.gcctrl[gclk] & AVR32_SCIF_GCCTRL_CEN_MASK)
    return -1;
  // Configure & start the generic clock.
  AVR32_SCIF.gcctrl[gclk] = ((opt->divider << AVR32_SCIF_GCCTRL_DIV_OFFSET)&AVR32_SCIF_GCCTRL_DIV_MASK)
                            |((opt->diven << AVR32_SCIF_GCCTRL_DIVEN_OFFSET)&AVR32_SCIF_GCCTRL_DIVEN_MASK)
                            |((opt->clock_source << AVR32_SCIF_GCCTRL_OSCSEL_OFFSET)&AVR32_SCIF_GCCTRL_OSCSEL_MASK)
                            |(AVR32_SCIF_GCCTRL_CEN_MASK);
  return PASS;
}
long int scif_start_osc (scif_osc_t osc, const scif_osc_opt_t * opt, bool wait_for_ready)
Configure and start an OSC0/OSC1 oscillator.
Parameters:
osc The oscillator to start [INPUT]
opt The configuration of the oscillator [INPUT]
wait_for_ready Wait for the oscillator to be stable before return [INPUT]
Note:
To avoid an infinite loop, this function checks the osc0 ready flag SCIF_POLL_TIMEOUT times.
Returns:
Status.
Return values:
0 Oscillator start successfull.
<0 Error starting the oscillator.
Configure and start an OSC0/OSC1 oscillator.
Power and Clocks Status Functions OSC0/OSC1 Functions
Definition at line 128 of file scif_uc3c.c.
References AVR32_ENTER_CRITICAL_REGION, AVR32_LEAVE_CRITICAL_REGION, ENABLE, scif_osc_opt_t::freq_hz, scif_osc_opt_t::gain, scif_osc_opt_t::mode, u_avr32_scif_oscctrl_t::OSCCTRL, PASS, SCIF_EXT_CRYSTAL_MAX_FREQ_HZ, SCIF_EXT_CRYSTAL_MIN_FREQ_HZ, SCIF_OSC0, SCIF_OSC_MODE_2PIN_CRYSTAL, SCIF_OSC_MODE_EXT_CLK, scif_pclksr_statushigh_wait(), SCIF_UNLOCK, and scif_osc_opt_t::startup.
{
  u_avr32_scif_oscctrl_t   u_avr32_scif_oscctrl;
#ifdef AVR32SFW_INPUT_CHECK
  // Check that the input frequency is in the supported frequency range.
  if( (opt->freq_hz < SCIF_EXT_CRYSTAL_MIN_FREQ_HZ)
      || (opt->freq_hz > SCIF_EXT_CRYSTAL_MAX_FREQ_HZ))
  {
    return -1;
  }
  // Check : for OSC0/OSC1, only 2 modes are supported
  if( (opt->mode != SCIF_OSC_MODE_EXT_CLK)
      && (opt->mode != SCIF_OSC_MODE_2PIN_CRYSTAL))
  {
    return -1;
  }
  if (osc == SCIF_OSC0)
  {
    // Check that the startup value is in the supported range.
    if(opt->startup > (unsigned char)AVR32_SCIF_OSCCTRL0_STARTUP_16384_RCOSC)
    {
      return -1;
    }
    // Check that the gain value is in the supported range.
    if(opt->gain > AVR32_SCIF_OSCCTRL0_GAIN_G3)
    {
      return -1;
    }
  }
  else
  {
    // Check that the startup value is in the supported range.
    if(opt->startup > (unsigned char)AVR32_SCIF_OSCCTRL1_STARTUP_16384_RCOSC)
    {
      return -1;
    }
    // Check that the gain value is in the supported range.
    if(opt->gain > AVR32_SCIF_OSCCTRL1_GAIN_G3)
    {
      return -1;
    }
  }
#endif  // AVR32SFW_INPUT_CHECK
  // Read Register
  u_avr32_scif_oscctrl.OSCCTRL[osc] = AVR32_SCIF.OSCCTRL[osc] ;
  // Modify: Configure & start OSC0.
  u_avr32_scif_oscctrl.OSCCTRL[osc].mode = opt->mode;
  u_avr32_scif_oscctrl.OSCCTRL[osc].gain = opt->gain;
  u_avr32_scif_oscctrl.OSCCTRL[osc].startup = opt->startup;
  u_avr32_scif_oscctrl.OSCCTRL[osc].oscen = ENABLE;
  AVR32_ENTER_CRITICAL_REGION( );
  // Unlock the write-protected OSCCTRL0 register
  SCIF_UNLOCK(AVR32_SCIF_OSCCTRL + 4*osc);
  // Write Back
  AVR32_SCIF.OSCCTRL[osc] = u_avr32_scif_oscctrl.OSCCTRL[osc];
  AVR32_LEAVE_CRITICAL_REGION( );
  if(true == wait_for_ready)
  {
    // Wait until OSC0 is stable and ready to be used.
    if(scif_pclksr_statushigh_wait(AVR32_SCIF_PCLKSR_OSC0RDY_MASK))
      return -1;
  }
  return PASS;
}
long int scif_start_osc32 (const scif_osc32_opt_t * opt, bool wait_for_ready)
Configure and start the OSC32 oscillator.
Parameters:
opt The configuration of the oscillator [INPUT]
wait_for_ready Wait for the oscillator to be stable before return [INPUT]
Note:
To avoid an infinite loop, this function checks the osc32 ready flag SCIF_POLL_TIMEOUT times.
Returns:
Status.
Return values:
0 Oscillator start successfull.
<0 Error starting the oscillator.
Definition at line 422 of file scif_uc3c.c.
References AVR32_ENTER_CRITICAL_REGION, AVR32_LEAVE_CRITICAL_REGION, ENABLE, scif_osc32_opt_t::freq_hz, scif_osc32_opt_t::mode, u_avr32_scif_oscctrl32_t::OSCCTRL32, u_avr32_scif_oscctrl32_t::oscctrl32, PASS, SCIF_EXT_CRYSTAL_MAX_FREQ_HZ, SCIF_EXT_CRYSTAL_MIN_FREQ_HZ, SCIF_OSC_MODE_2PIN_CRYSTAL, SCIF_OSC_MODE_EXT_CLK, scif_pclksr_statushigh_wait(), SCIF_UNLOCK, and scif_osc32_opt_t::startup.
{
  u_avr32_scif_oscctrl32_t  u_avr32_scif_oscctrl32;
#ifdef AVR32SFW_INPUT_CHECK
  // Check that the input frequency is in the supported frequency range.
  if( (opt->freq_hz < SCIF_EXT_CRYSTAL_MIN_FREQ_HZ)
      || (opt->freq_hz > SCIF_EXT_CRYSTAL_MAX_FREQ_HZ))
  {
    return -1;
  }
  // Check : for OSC0/OSC1, only 2 modes are supported
  if( (opt->mode < SCIF_OSC_MODE_EXT_CLK)
      || (opt->mode > SCIF_OSC_MODE_2PIN_CRYSTAL)
      || (opt->mode == SCIF_OSC_MODE_NOT_SUPPORTED_1)
      || (opt->mode == SCIF_OSC_MODE_NOT_SUPPORTED_2) )
  {
    return -1;
  }
  // Check that the startup value is in the supported range.
  if(opt->startup > (unsigned char)AVR32_SCIF_OSCCTRL32_STARTUP_524288_RCOSC)
  {
    return -1;
  }
#endif  // AVR32SFW_INPUT_CHECK
  // Read Register
  u_avr32_scif_oscctrl32.oscctrl32 = AVR32_SCIF.oscctrl32 ;
  // Modify : Configure & start OSC32.
  u_avr32_scif_oscctrl32.OSCCTRL32.mode = opt->mode;
  u_avr32_scif_oscctrl32.OSCCTRL32.startup = opt->startup;
  u_avr32_scif_oscctrl32.OSCCTRL32.osc32en = ENABLE;
  AVR32_ENTER_CRITICAL_REGION( );
  // Unlock the write-protected OSCCTRL32 register
  SCIF_UNLOCK(AVR32_SCIF_OSCCTRL32);
  // Write Back
  AVR32_SCIF.oscctrl32 = u_avr32_scif_oscctrl32.oscctrl32;
  AVR32_LEAVE_CRITICAL_REGION( );
  if(true == wait_for_ready)
  {
    // Wait until OSC32 is stable and ready to be used.
    if(scif_pclksr_statushigh_wait(AVR32_SCIF_PCLKSR_OSC32RDY_MASK))
      return -1;
  }
  return PASS;
}
void scif_start_rc120M (void)
Start the 120MHz internal RCosc (RC120M) clock.
Definition at line 532 of file scif_uc3c.c.
References AVR32_ENTER_CRITICAL_REGION, AVR32_LEAVE_CRITICAL_REGION, and SCIF_UNLOCK.
Referenced by pcl_configure_clocks_rc120m().
{
  AVR32_ENTER_CRITICAL_REGION( );
  // Unlock the write-protected RC120MCR register
  SCIF_UNLOCK(AVR32_SCIF_RC120MCR);
  AVR32_SCIF.rc120mcr = AVR32_SCIF_RC120MCR_EN_MASK;
  AVR32_LEAVE_CRITICAL_REGION( );
}
void scif_start_rc8M (void)
Start the 8MHz internal RCosc (RC8M) clock.
Start the 8MHz internal RCosc (RC8M) clock.
Critical Path Oscillator Functions 8MHz RCosc Functions
Definition at line 506 of file scif_uc3c.c.
References AVR32_ENTER_CRITICAL_REGION, AVR32_LEAVE_CRITICAL_REGION, and SCIF_UNLOCK.
{
  unsigned int* calibration_bits = (unsigned int*)0x80800200;
  AVR32_ENTER_CRITICAL_REGION( );
  // Unlock the write-protected RC8MCR register
  SCIF_UNLOCK(AVR32_SCIF_RCCR8);
  AVR32_SCIF.rccr8 = AVR32_SCIF_RCCR8_RCOSC8_EN_MASK | ((*calibration_bits)&AVR32_SCIF_RCCR8_CALIB_MASK);
  AVR32_LEAVE_CRITICAL_REGION( );
}
long int scif_stop_gclk (unsigned int gclk)
Stop a generic clock.
Parameters:
gclk The generic clock number to stop.
Note:
To avoid an infinite loop, this function checks the Clock enable flag SCIF_POLL_TIMEOUT times.
Returns:
Status.
Return values:
0 Success.
<0 Unable to stop generic clock.
Definition at line 588 of file scif_uc3c.c.
References PASS, and SCIF_POLL_TIMEOUT.
Referenced by scif_gc_setup().
{
  unsigned int  timeout = SCIF_POLL_TIMEOUT;
#ifdef AVR32SFW_INPUT_CHECK
  // Check that the generic clock number is correct
  if( gclk > AVR32_SCIF_GCLK_NUM )
  {
    return -1;
  }
#endif  // AVR32SFW_INPUT_CHECK
  // Stop the generic clock.
  AVR32_SCIF.gcctrl[gclk] &= ~AVR32_SCIF_GCCTRL_CEN_MASK;
  // Wait until the generic clock is actually stopped.
  while(AVR32_SCIF.gcctrl[gclk] & AVR32_SCIF_GCCTRL_CEN_MASK)
  {
    if(--timeout == 0)
      return -1;
  }
  return PASS;
}
long int scif_stop_osc (scif_osc_t osc)
Stop an oscillator.
Parameters:
osc The oscillator to stop
Returns:
Status.
Return values:
0 Oscillator successfully stopped.
<0 An error occured when stopping the oscillator.
Definition at line 210 of file scif_uc3c.c.
References AVR32_ENTER_CRITICAL_REGION, AVR32_LEAVE_CRITICAL_REGION, PASS, and SCIF_UNLOCK.
{
  unsigned long temp;
  temp = AVR32_SCIF.oscctrl[osc];
  temp &= ~(AVR32_SCIF_OSCCTRL_OSCEN_DISABLE << AVR32_SCIF_OSCCTRL_OSCEN_OFFSET);
  AVR32_ENTER_CRITICAL_REGION( );
  // Unlock the write-protected OSCCTRL0 register
  SCIF_UNLOCK(AVR32_SCIF_OSCCTRL + 4*osc);
  // Stop OSC0.
  AVR32_SCIF.oscctrl[osc] = temp;
  AVR32_LEAVE_CRITICAL_REGION( );
  return PASS;
}
long int scif_stop_osc32 (void)
Stop the OSC32 oscillator.
Returns:
Status.
Return values:
0 Oscillator successfully stopped.
<0 An error occured when stopping the oscillator.
Definition at line 476 of file scif_uc3c.c.
References AVR32_ENTER_CRITICAL_REGION, AVR32_LEAVE_CRITICAL_REGION, PASS, and SCIF_UNLOCK.
{
  unsigned long temp = AVR32_SCIF.oscctrl32;
  temp &= ~(AVR32_SCIF_OSCCTRL32_OSC32EN_DISABLE << AVR32_SCIF_OSCCTRL32_OSC32EN_OFFSET);
  AVR32_ENTER_CRITICAL_REGION( );
  // Unlock the write-protected OSCCTRL32 register
  SCIF_UNLOCK(AVR32_SCIF_OSCCTRL32);
  // Stop OSC32.
  AVR32_SCIF.oscctrl32 = temp;
  AVR32_LEAVE_CRITICAL_REGION( );
  return PASS;
}
void scif_stop_rc120M (void)
Stop the 120MHz internal RCosc (RC120M) clock.
Definition at line 541 of file scif_uc3c.c.
References AVR32_ENTER_CRITICAL_REGION, AVR32_LEAVE_CRITICAL_REGION, and SCIF_UNLOCK.
{
  unsigned long temp = AVR32_SCIF.rc120mcr;
  AVR32_ENTER_CRITICAL_REGION( );
  // Unlock the write-protected RC120MCR register
  SCIF_UNLOCK(AVR32_SCIF_RC120MCR);
  temp &= ~AVR32_SCIF_RC120MCR_EN_MASK;
  AVR32_SCIF.rc120mcr = temp;
  AVR32_LEAVE_CRITICAL_REGION( );
}
void scif_stop_rc8M (void)
Stop the 8MHz internal RCosc (RC8M) clock.
Definition at line 516 of file scif_uc3c.c.
References AVR32_ENTER_CRITICAL_REGION, AVR32_LEAVE_CRITICAL_REGION, and SCIF_UNLOCK.
{
  unsigned long temp = AVR32_SCIF.rccr8;
  AVR32_ENTER_CRITICAL_REGION( );
  // Unlock the write-protected RC8MCR register
  SCIF_UNLOCK(AVR32_SCIF_RCCR8);
  temp &= ~AVR32_SCIF_RCCR8_RCOSC8_EN_MASK;
  AVR32_SCIF.rccr8 = temp;
  AVR32_LEAVE_CRITICAL_REGION( );
}
static void scif_temperature_sensor_disable (void) [inline, static]
Disable the temperature sensor.
Note:
Due to register unlock process, this function needs to be atomic so if there's risk that call is split by an interrupt, disable them first.
Definition at line 747 of file scif_uc3c.h.
References SCIF_UNLOCK.
{
  // Unlock the write-protected TSENS register
  SCIF_UNLOCK(AVR32_SCIF_TSENS);
  AVR32_SCIF.tsens = ~AVR32_SCIF_TSENS_EN_MASK;
}
static void scif_temperature_sensor_enable (void) [inline, static]
Enable the temperature sensor.
Note:
Due to register unlock process, this function needs to be atomic. So if there's risk that call is split by any interrupts, disable them first.
Definition at line 731 of file scif_uc3c.h.
References SCIF_UNLOCK.
{
  // Unlock the write-protected TSENS register
  SCIF_UNLOCK(AVR32_SCIF_TSENS);
  AVR32_SCIF.tsens = AVR32_SCIF_TSENS_EN_MASK;
}
long int scif_wait_for_pll_locked (scif_pll_t pll)
This function will wait for PLL locked.
Parameters:
pll The PLL to configure [INPUT]
Returns:
Status.
Return values:
0 PLL successfully started
<0 Error starting the PLL.
Definition at line 401 of file scif_uc3c.c.
References PASS, and SCIF_PLL0.
Referenced by local_start_highfreq_clock(), and pcl_configure_usb_clock().
{
  if (pll == SCIF_PLL0)
  {
      // Wait until PLL0 is stable and ready to be used.
      while(!(AVR32_SCIF.pclksr & AVR32_SCIF_PCLKSR_PLL0_LOCK_MASK));
  }
  else
  {
      // Wait until PLL1 is stable and ready to be used.
      while(!(AVR32_SCIF.pclksr & AVR32_SCIF_PCLKSR_PLL1_LOCK_MASK));
  }
  return PASS;
}
void scif_write_gplp (int gplp, unsigned long value)
Write into the SCIF GPLP registers.
Parameters:
gplp GPLP register index (0,1,... depending on the number of GPLP registers for a given part)
value Value to write
Definition at line 106 of file scif_uc3c.c.
References SCIF_UNLOCK.
{
  SCIF_UNLOCK(AVR32_SCIF_GPLP + 4*gplp);
  AVR32_SCIF.gplp[gplp] = value;
}